import express from "express";
import userRouter from "./usersRoutes.js";
import authRouter from "./authRoutes.js";
import commonRouter from "./commonRoutes.js";
import cottonRouter from "./cottonRoutes.js";
import yarnRouter from "./yarnRoutes.js";
import storesRouter from "./storesRoutes.js";
import hrmRouter from "./hrmRoutes.js";
import gateRouter from "./gateRoutes.js";
import financeRouter from "./financeRoutes.js";
import wasteRouter from "./wasteRoutes.js";
import mechanicalRouter from "./mehanicalRoutes.js";
import cottonOverviewRouter from "./cottonOverviewRoutes.js";
import yarnOverviewRouter from "./yarnOverviewRoutes.js";
import storeOverviewRouter from "./storeOverviewRoutes.js";
import hrmOverviewRouter from "./hrmOverviewRoutes.js";
import gateOverviewRouter from "./gateOverviewRoutes.js";
import financeOverviewRouter from "./financeOverviewRoutes.js";
import cottonReportRoutes from "./cottonReportRoutes.js";
import yarnReportRoutes from "./yarnReportRoutes.js";
import storeReportRoutes from "./storeReportRoutes.js";
import hrmReportRoutes from "./hrmReportRoutes.js";
import payrollReportRoutes from "./payrollReportRoutes.js";
import productionReportRoutes from "./productionReportRoutes.js";
import wasteReportRoutes from "./wasteReportRoutes.js";
import mechanicalReportRoutes from "./mechanicalReportRoutes.js";
import electricalReportRoutes from "./electricalReportRoutes.js";
import weighbridgeReportRoutes from "./weighbridgeReportRoutes.js";
import costingReportRoutes from "./costingReportRoutes.js";
import documentReportRoutes from "./documentReportRoutes.js";
import graphRoutes from "./graphRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import locationRoutes from "./loginLogsRoutes.js";
import { testDBConnection } from "../controllers/testController.js";
import bullMQRoutes from "../routes/bullMQRoutes.js";
import {
  getNotificationCount,
  notificationUpdate,
  saveFCMToken,
} from "../controllers/notifications.comtroller.js";
import { authenticate } from "../middleware/authMiddleware.js";
import notificationRouter from "./notificationRoutes.js";
import employeeAllotment from "./employeeAllotmentRoutes.js";
import pdfReport from "./pdfReportRoutes.js";
import bankRouter from "./bankRoutes.js";
import maintenanceGroupRouter from "./maintenanceGroupRoutes.js";
import plantGroupRouter from "./plantGroupRoutes.js";
import solarGroupRouter from "./solarGroupRoutes.js";
import solarLocationRouter from "./solarLocationRoutes.js";
import ebMeterRouter from "./ebMeterMasterRoutes.js";
import plantMasterRouter from "./plantMasterRoutes.js";
import slotRouter from "./slotRoutes.js";
import generatorMachineGroupRouter from "./generatorMachineGroupRoutes.js";
import powerCategoryRouter from "./powerCategoryRoutes.js";
import compressorGroupMasterRouter from "./compressorGroupMasterRoutes.js";
import machineGroupRouter from "./machineGroupRoutes.js";
import ebRateRouter from "./ebRateRoutes.js";
import electricalScheduleRouter from "./electricalScheduleRoutes.js";
import breakdownRouter from "./breakdownRoutes.js";
import workOrderRouter from "./workOrderRoutes.js";
import empEngagedRouter from "./empEngagedRoutes.js";
import powerFailureRouter from "./powerFailureRoutes.js";
import electricalReadingRouter from "./electricalReadingRoutes.js";
import machineTapeCutRouter from "./machineTapeCutRoutes.js";
import maintenanceBuffingRouter from "./maintenanceBuffingRoutes.js";
import maintenanceDesignationRouter from "./maintenanceDesignationRoutes.js";
import departmentGroupRouter from "./departmentGroupRoutes.js";
import departmentRouter from "./departmentRoutes.js";
import companyRouter from "./companyRoutes.js";
import approvalRouter from "./approvalRoutes.js";
import costHeadRouter from "./costHeadRoutes.js";
import stateRouter from "./stateRoutes.js";
import godownRouter from "./godownRoutes.js";
import districtRouter from "./districtRoutes.js";
import costingMasterRouter from "./costingMasterRoutes.js";
import itemCategoryRouter from "./itemCategoryRoutes.js";
import taxRouter from "./taxRoutes.js";
import itemUomRouter from "./itemUomRoutes.js";
import itemUsageTypeRouter from "./itemUsageTypeRoutes.js";
import itemGroupRouter from "./itemGroupRoutes.js";
import itemRouter from "./itemRoutes.js";
import machineRouter from "./machineRoutes.js";
import machineMakeRouter from "./machineMakeRoutes.js";
import machineTypeRouter from "./machineTypeRoutes.js";
import vehicleMakeRouter from "./vehicleMakeRoutes.js";
import vehicleCapacityRouter from "./vehicleCapacityRoutes.js";
import vehicleRouter from "./vehicleRoutes.js";
import vehicleExpensesGroupRouter from "./vehicleExpensesGroupRoutes.js";
import vehicleExpensesRouter from "./vehicleExpensesRoutes.js";
import vehicleExpensesEntryRouter from "./vehicleExpensesEntryRoutes.js";
import agentRouter from "./agentRoutes.js";
import customerApproveRouter from "./customerApproveRoutes.js";
import customerRouter from "./customerRoutes.js";
import customerTypeRouter from "./customerTypeRoutes.js";
import supplierApproveRouter from "./supplierApproveRoutes.js";
import supplierRouter from "./supplierRoutes.js";
import transporterRouter from "./transporterRoutes.js";
import rawMaterialTypeRouter from "./rawMaterialTypeRoutes.js";
import rawMaterialRouter from "./rawMaterialRoutes.js";
import cottonCountRouter from "./cottonCountRoutes.js";
import countGroupRouter from "./countGroupRoutes.js";
import countNameRouter from "./countNameRoutes.js";
import countTypeRouter from "./countTypeRoutes.js";
import lotNoRouter from "./lotNoRoutes.js";
import tipColourRouter from "./tipColourRoutes.js";
import bagColourRouter from "./bagColourRoutes.js";
import salesTypeRouter from "./salesTypeRoutes.js";
import taxTypeRouter from "./taxTypeRoutes.js";
import otherChargesRouter from "./otherChargesRoutes.js";
import salesInchargeRouter from "./salesInchargeRoutes.js";
import yarnBagNoGroupRouter from "./yarnBagNoGroupRoutes.js";
import yarnBagNoSettingRouter from "./yarnBagNoSettingRoutes.js";
import boxPackingRouter from "./boxPackingRoutes.js";
import yarnProductionRouter from "./yarnProductionRoutes.js";
import yarnFixingRouter from "./yarnFixingRoutes.js";
import yarnOnlinePackingRouter from "./yarnOnlinePackingRoutes.js";
import yarnConePackingRouter from "./yarnConePackingRoutes.js";
import yarnSalesOrderRouter from "./yarnSalesOrderRoutes.js";
import yarnSalesOrderApprovalRouter from "./yarnSalesOrderApprovalRoutes.js";
import yarnSalesOrderPrintRouter from "./yarnSalesOrderPrintRoutes.js";
import yarnSalesOrderAdjustmentRouter from "./yarnSalesOrderAdjustmentRoutes.js";
import yarnInvoiceDeleteRouter from "./yarnInvoiceDeleteRoutes.js";
import yarnBillConfirmationRouter from "./yarnBillConfirmationRoutes.js";
import yarnDuplicateBillPrintRouter from "./yarnDuplicateBillPrintRoutes.js";
import yarnGatePassRouter from "./yarnGatePassRoutes.js";
import yarnInvoiceFullRouter from "./yarnInvoiceFullRoutes.js";
import yarnInvoiceCancelRouter from "./yarnInvoiceCancelRoutes.js";
import yarnDespatchPackingRouter from "./yarnDespatchPackingRoutes.js";
import yarnDespatchAdviceRouter from "./yarnDespatchAdviceRoutes.js";
import yarnSalesReturnRouter from "./yarnSalesReturnRoutes.js";
import cottonPackingMaterialRouter from "./cottonPackingMaterialRoutes.js";
import stationRouter from "./stationRoutes.js";
import cqtParameterRouter from "./cqtParameterRoutes.js";
import cqtStdRouter from "./cqtStdRoutes.js";
import serviceOrderExpensesRouter from "./serviceOrderExpensesRoutes.js";
import commonServiceActivityRouter from "./commonServiceActivityRoutes.js";
import machineServiceScheduleRouter from "./machineServiceScheduleRoutes.js";
import serviceActivityRouter from "./serviceActivityRoutes.js";
import typeOfBreakdownRouter from "./typeOfBreakdownRoutes.js";
import roleMenuRouter from "./roleMenuRoutes.js";
import einvoiceRouter from "./einvoiceRoutes.js";
import goodsInOutTypeRouter from "./goodsInOutTypeRoutes.js";
import materialTypeRouter from "./materialTypeRoutes.js";
import mixingNameRouter from "./mixingNameRoutes.js";
import stoppageGroupRouter from "./stoppageGroupRoutes.js";
import stoppageReasonRouter from "./stoppageReasonRoutes.js";
import cardingMachineSettingRouter from "./cardingMachineSettingRoutes.js";
import cardingProductionRouter from "./cardingProductionRoutes.js";
import drawingMachineSettingRouter from "./drawingMachineSettingRoutes.js";
import drawingProductionRouter from "./drawingProductionRoutes.js";
import unilapMachineSettingRouter from "./unilapMachineSettingRoutes.js";
import unilapProductionRouter from "./unilapProductionRoutes.js";
import comberMachineSettingRouter from "./comberMachineSettingRoutes.js";
import comberProductionRouter from "./comberProductionRoutes.js";
import finisherDrawingMachineSettingRouter from "./finisherDrawingMachineSettingRoutes.js";
import finisherDrawingProductionRouter from "./finisherDrawingProductionRoutes.js";
import simplexMachineSettingRouter from "./simplexMachineSettingRoutes.js";
import simplexProductionRouter from "./simplexProductionRoutes.js";
import spinningCountSettingRouter from "./spinningCountSettingRoutes.js";
import spinningFrameSettingRouter from "./spinningFrameSettingRoutes.js";
import spinningProductionRouter from "./spinningProductionRoutes.js";
import spinningStopReasonRouter from "./spinningStopReasonRoutes.js";
import autoconerCountSettingRouter from "./autoconerCountSettingRoutes.js";
import autoconerMachineSettingRouter from "./autoconerMachineSettingRoutes.js";
import autoconerProductionRouter from "./autoconerProductionRoutes.js";
import autoconerCountWiseProductionRouter from "./autoconerCountWiseProductionRoutes.js";
import ycpProductionRouter from "./ycpProductionRoutes.js";
import oeCountSettingRouter from "./oeCountSettingRoutes.js";
import oeFrameSettingRouter from "./oeFrameSettingRoutes.js";
import oeProductionRouter from "./oeProductionRoutes.js";
import prodnEmpEngagedRouter from "./prodnEmpEngagedRoutes.js";
import productionDataDownloadRouter from "./productionDataDownloadRoutes.js";
import wasteItemGroupRouter from "./wasteItemGroupRoutes.js";
import wasteItemRouter from "./wasteItemRoutes.js";
import usableWasteItemRouter from "./usableWasteItemRoutes.js";
import wasteProductionRouter from "./wasteProductionRoutes.js";
import usableWasteProductionRouter from "./usableWasteProductionRoutes.js";
import usableWasteIssueRouter from "./usableWasteIssueRoutes.js";
import wasteDCRouter from "./wasteDCRoutes.js";
import wasteInvoiceRouter from "./wasteInvoiceRoutes.js";
import wasteInvoiceApprovalRouter from "./wasteInvoiceApprovalRoutes.js";
import scrapInvoiceRouter from "./scrapInvoiceRoutes.js";
import accountGroupRouter from "./accountGroupRoutes.js";
import cottonPurchaseOrderRouter from "./cottonPurchaseOrderRoutes.js";
import cottonPurchaseOrderAmendmentRouter from "./cottonPurchaseOrderAmendmentRoutes.js";
import cottonPurchaseOrderCancelRouter from "./cottonPurchaseOrderCancelRoutes.js";
import cottonQualityTestApprovalRouter from "./cottonQualityTestApprovalRoutes.js";
import cottonGodownTransferRouter from "./cottonGodownTransferRoutes.js";
import cottonArrivalRouter from "./cottonArrivalRoutes.js";
import cottonWeighmentRouter from "./cottonWeighmentRoutes.js";
import cottonWeighmentApprovalRouter from "./cottonWeighmentApprovalRoutes.js";
import cottonQualityTestRouter from "./cottonQualityTestRoutes.js";
import cottonLotApprovalRouter from "./cottonLotApprovalRoutes.js";
import cottonMixingIssueRequisitionRouter from "./cottonMixingIssueRequisitionRoutes.js";
import cottonIssueRouter from "./cottonIssueRoutes.js";
import cottonSalesRouter from "./cottonSalesRoutes.js";
import cottonSalesReturnRouter from "./cottonSalesReturnRoutes.js";
import cottonRejectRouter from "./cottonRejectRoutes.js";
import cottonRejectLotPendingRouter from "./cottonRejectLotPendingRoutes.js";
import cottonAllowanceRouter from "./cottonAllowanceRoutes.js";
import cottonWeightApprovalRouter from "./cottonWeightApprovalRoutes.js";
import itemRequisitionRouter from "./itemRequisitionRoutes.js";
import itemRequisitionAdjustmentRouter from "./itemRequisitionAdjustmentRoutes.js";
import itemIndentRouter from "./itemIndentRoutes.js";
import purchaseOrderRouter from "./purchaseOrderRoutes.js";
import inwardRouter from "./inwardRoutes.js";
import purchaseReturnRouter from "./purchaseReturnRoutes.js";
import purchaseOrderPrintRouter from "./purchaseOrderPrintRoutes.js";
import indentApproval1Router from "./indentApproval1Routes.js";
import indentApproval2Router from "./indentApproval2Routes.js";
import directIssueRouter from "./directIssueRoutes.js";
import purchaseRequisitionApprovalRouter from "./purchaseRequisitionApprovalRoutes.js";
import goodsInPassRouter from "./goodsInPassRoutes.js";
import goodsOutPassRouter from "./goodsOutPassRoutes.js";
import gstRouter from "./gstRoutes.js";
import companyVisitorsRouter from "./companyVisitorsRoutes.js";
import vehicleInOutRouter from "./vehicleInOutRoutes.js";
import gradeRouter from "./gradeRoutes.js";
import employmentRouter from "./employmentRoutes.js";
import payHeadRouter from "./payHeadRoutes.js";
import holidayRouter from "./holidayRoutes.js";
import manualEntryReasonRouter from "./manualEntryReasonRoutes.js";
import routeRouter from "./routeRoutes.js";
import routeVehicleRouter from "./routeVehicleRoutes.js";

const router = express.Router();

const appRoutes = () => {
  router.use("/user", userRouter);
  router.use("/auth", authRouter);
  router.use("/badge", commonRouter);
  router.use("/cotton", cottonRouter);
  router.use("/cotton/overview", cottonOverviewRouter);
  router.use("/yarn", yarnRouter);
  router.use("/yarn/overview", yarnOverviewRouter);
  router.use("/stores", storesRouter);
  router.use("/stores/overview", storeOverviewRouter);
  router.use("/hrm", hrmRouter);
  router.use("/hrm/overview", hrmOverviewRouter);
  router.use("/gate", gateRouter);
  router.use("/gate/overview", gateOverviewRouter);
  router.use("/company-visitors", companyVisitorsRouter);
  router.use("/vehicle-in-out", vehicleInOutRouter);
  router.use("/grade", gradeRouter);
  router.use("/employment", employmentRouter);
  router.use("/pay-head", payHeadRouter);
  router.use("/holiday", holidayRouter);
  router.use("/manual-entry-reason", manualEntryReasonRouter);
  router.use("/route", routeRouter);
  router.use("/route-vehicle", routeVehicleRouter);
  router.use("/finance", financeRouter);
  router.use("/finance/overview", financeOverviewRouter);
  router.use("/bank", bankRouter);
  router.use("/maintenance-group", maintenanceGroupRouter);
  router.use("/plant-group", plantGroupRouter);
  router.use("/solar-group", solarGroupRouter);
  router.use("/solar-location", solarLocationRouter);
  router.use("/eb-meter", ebMeterRouter);
  router.use("/plant-master", plantMasterRouter);
  router.use("/slot", slotRouter);
  router.use("/generator-machine-group", generatorMachineGroupRouter);
  router.use("/power-category", powerCategoryRouter);
  router.use("/compressor-group-master", compressorGroupMasterRouter);
  router.use("/machine-group", machineGroupRouter);
  router.use("/eb-rate", ebRateRouter);
  router.use("/electrical-schedule", electricalScheduleRouter);
  router.use("/breakdown", breakdownRouter);
  router.use("/work-order", workOrderRouter);
  router.use("/emp-engaged", empEngagedRouter);
  router.use("/power-failure", powerFailureRouter);
  router.use("/electrical-reading", electricalReadingRouter);
  router.use("/machine-tape-cut", machineTapeCutRouter);
  router.use("/maintenance-buffing", maintenanceBuffingRouter);
  router.use("/maintenance-designation", maintenanceDesignationRouter);
  router.use("/department-group", departmentGroupRouter);
  router.use("/department", departmentRouter);
  router.use("/approval", approvalRouter);
  router.use("/cost-head", costHeadRouter);
  router.use("/state", stateRouter);
  router.use("/godown", godownRouter);
  router.use("/district", districtRouter);
  router.use("/costing-master", costingMasterRouter);
  router.use("/item-category", itemCategoryRouter);
  router.use("/tax", taxRouter);
  router.use("/item-uom", itemUomRouter);
  router.use("/item-usage-type", itemUsageTypeRouter);
  router.use("/item-group", itemGroupRouter);
  router.use("/item", itemRouter);
  router.use("/machine", machineRouter);
  router.use("/machine-make", machineMakeRouter);
  router.use("/machine-type", machineTypeRouter);
  router.use("/vehicle-make", vehicleMakeRouter);
  router.use("/vehicle-capacity", vehicleCapacityRouter);
  router.use("/vehicle-expenses-group", vehicleExpensesGroupRouter);
  router.use("/vehicle-expenses-entry", vehicleExpensesEntryRouter);
  router.use("/vehicle-expenses", vehicleExpensesRouter);
  router.use("/vehicle", vehicleRouter);
  router.use("/agent", agentRouter);
  router.use("/customer-approve", customerApproveRouter);
  router.use("/customer", customerRouter);
  router.use("/customer-type", customerTypeRouter);
  router.use("/supplier-approve", supplierApproveRouter);
  router.use("/supplier", supplierRouter);
  router.use("/transporter", transporterRouter);
  router.use("/raw-material-type", rawMaterialTypeRouter);
  router.use("/raw-material", rawMaterialRouter);
  router.use("/cotton-count", cottonCountRouter);
  router.use("/count-group", countGroupRouter);
  router.use("/count-name", countNameRouter);
  router.use("/count-type", countTypeRouter);
  router.use("/lot-no", lotNoRouter);
  router.use("/tip-colour", tipColourRouter);
  router.use("/bag-colour", bagColourRouter);
  router.use("/sales-type", salesTypeRouter);
  router.use("/tax-type", taxTypeRouter);
  router.use("/other-charges", otherChargesRouter);
  router.use("/sales-incharge", salesInchargeRouter);
  router.use("/yarn-bag-no-group", yarnBagNoGroupRouter);
  router.use("/yarn-bag-no-setting", yarnBagNoSettingRouter);
  router.use("/box-packing", boxPackingRouter);
  router.use("/yarn-production", yarnProductionRouter);
  router.use("/yarn-fixing", yarnFixingRouter);
  router.use("/yarn-online-packing", yarnOnlinePackingRouter);
  router.use("/yarn-cone-packing", yarnConePackingRouter);
  router.use("/yarn-sales-order", yarnSalesOrderRouter);
  router.use("/yarn-sales-order-approval", yarnSalesOrderApprovalRouter);
  router.use("/yarn-sales-order-print", yarnSalesOrderPrintRouter);
  router.use("/yarn-sales-order-adjustment", yarnSalesOrderAdjustmentRouter);
  router.use("/yarn-invoice-delete", yarnInvoiceDeleteRouter);
  router.use("/yarn-bill-confirmation", yarnBillConfirmationRouter);
  router.use("/yarn-duplicate-bill-print", yarnDuplicateBillPrintRouter);
  router.use("/yarn-gate-pass", yarnGatePassRouter);
  router.use("/yarn-invoice-full", yarnInvoiceFullRouter);
  router.use("/yarn-invoice-cancel", yarnInvoiceCancelRouter);
  router.use("/yarn-despatch-packing", yarnDespatchPackingRouter);
  router.use("/yarn-despatch-advice", yarnDespatchAdviceRouter);
  router.use("/yarn-sales-return", yarnSalesReturnRouter);
  router.use("/cotton-packing-material", cottonPackingMaterialRouter);
  router.use("/station", stationRouter);
  router.use("/cqt-parameter", cqtParameterRouter);
  router.use("/cqt-std", cqtStdRouter);
  router.use("/goods-in-out-type", goodsInOutTypeRouter);
  router.use("/material-type", materialTypeRouter);
  router.use("/mixing-name", mixingNameRouter);
  router.use("/stoppage-group", stoppageGroupRouter);
  router.use("/stoppage-reason", stoppageReasonRouter);
  router.use("/carding-machine-setting", cardingMachineSettingRouter);
  router.use("/carding-production", cardingProductionRouter);
  router.use("/drawing-machine-setting", drawingMachineSettingRouter);
  router.use("/drawing-production", drawingProductionRouter);
  router.use("/unilap-machine-setting", unilapMachineSettingRouter);
  router.use("/unilap-production", unilapProductionRouter);
  router.use("/comber-machine-setting", comberMachineSettingRouter);
  router.use("/comber-production", comberProductionRouter);
  router.use("/finisher-drawing-machine-setting", finisherDrawingMachineSettingRouter);
  router.use("/finisher-drawing-production", finisherDrawingProductionRouter);
  router.use("/simplex-machine-setting", simplexMachineSettingRouter);
  router.use("/simplex-production", simplexProductionRouter);
  router.use("/spinning-count-setting", spinningCountSettingRouter);
  router.use("/spinning-frame-setting", spinningFrameSettingRouter);
  router.use("/spinning-production", spinningProductionRouter);
  router.use("/spinning-stop-reason", spinningStopReasonRouter);
  router.use("/autoconer-count-setting", autoconerCountSettingRouter);
  router.use("/autoconer-machine-setting", autoconerMachineSettingRouter);
  router.use("/autoconer-production", autoconerProductionRouter);
  router.use("/autoconer-count-wise-production", autoconerCountWiseProductionRouter);
  router.use("/ycp-production", ycpProductionRouter);
  router.use("/oe-count-setting", oeCountSettingRouter);
  router.use("/oe-frame-setting", oeFrameSettingRouter);
  router.use("/oe-production", oeProductionRouter);
  router.use("/prodn-emp-engaged", prodnEmpEngagedRouter);
  router.use("/production-data-download", productionDataDownloadRouter);
  router.use("/waste-item-group", wasteItemGroupRouter);
  router.use("/waste-item", wasteItemRouter);
  router.use("/usable-waste-item", usableWasteItemRouter);
  router.use("/waste-production", wasteProductionRouter);
  router.use("/usable-waste-production", usableWasteProductionRouter);
  router.use("/usable-waste-issue", usableWasteIssueRouter);
  router.use("/waste-dc", wasteDCRouter);
  router.use("/waste-invoice", wasteInvoiceRouter);
  router.use("/waste-invoice-approval", wasteInvoiceApprovalRouter);
  router.use("/scrap-invoice", scrapInvoiceRouter);
  router.use("/account-group", accountGroupRouter);
  router.use("/cotton-purchase-order", cottonPurchaseOrderRouter);
  router.use("/cotton-purchase-order-amendment", cottonPurchaseOrderAmendmentRouter);
  router.use("/cotton-purchase-order-cancel", cottonPurchaseOrderCancelRouter);
  router.use("/cotton-quality-test-approval", cottonQualityTestApprovalRouter);
  router.use("/cotton-godown-transfer", cottonGodownTransferRouter);
  router.use("/cotton-arrival", cottonArrivalRouter);
  router.use("/cotton-weighment", cottonWeighmentRouter);
  router.use("/cotton-weighment-approval", cottonWeighmentApprovalRouter);
  router.use("/cotton-quality-test", cottonQualityTestRouter);
  router.use("/cotton-lot-approval", cottonLotApprovalRouter);
  router.use("/cotton-mixing-issue-requisition", cottonMixingIssueRequisitionRouter);
  router.use("/cotton-issue", cottonIssueRouter);
  router.use("/cotton-sales", cottonSalesRouter);
  router.use("/cotton-sales-return", cottonSalesReturnRouter);
  router.use("/cotton-reject", cottonRejectRouter);
  router.use("/cotton-reject-lot-pending", cottonRejectLotPendingRouter);
  router.use("/cotton-allowance", cottonAllowanceRouter);
  router.use("/cotton-weight-approval", cottonWeightApprovalRouter);
  router.use("/item-requisition", itemRequisitionRouter);
  router.use("/item-requisition-adjustment", itemRequisitionAdjustmentRouter);
  router.use("/item-indent", itemIndentRouter);
  router.use("/purchase-order", purchaseOrderRouter);
  router.use("/inward", inwardRouter);
  router.use("/purchase-return", purchaseReturnRouter);
  router.use("/purchase-order-print", purchaseOrderPrintRouter);
  router.use("/indent-approval-1", indentApproval1Router);
  router.use("/indent-approval-2", indentApproval2Router);
  router.use("/direct-issue", directIssueRouter);
  router.use("/purchase-requisition-approval", purchaseRequisitionApprovalRouter);
  router.use("/goods-in-pass", goodsInPassRouter);
  router.use("/goods-out-pass", goodsOutPassRouter);
  router.use("/gst", gstRouter);
  router.use("/service-order-expenses", serviceOrderExpensesRouter);
  router.use("/common-service-activity", commonServiceActivityRouter);
  router.use("/machine-service-schedule", machineServiceScheduleRouter);
  router.use("/service-activity", serviceActivityRouter);
  router.use("/type-of-breakdown", typeOfBreakdownRouter);
  router.use("/mechanical", mechanicalRouter);
  router.use("/role-access", roleMenuRouter);
  router.use("/einvoice", einvoiceRouter);

  //REPORTS
  router.use("/cotton/reports", cottonReportRoutes);
  router.use("/yarn/reports", yarnReportRoutes);
  router.use("/store/reports", storeReportRoutes);
  router.use("/hrm/reports", hrmReportRoutes);
  router.use("/payroll/reports", payrollReportRoutes);
  router.use("/production/reports", productionReportRoutes);
  router.use("/waste/reports", wasteReportRoutes);
  router.use("/mechanical/reports", mechanicalReportRoutes);
  router.use("/electrical/reports", electricalReportRoutes);
  router.use("/weighbridge/reports", weighbridgeReportRoutes);
  router.use("/costing/reports", costingReportRoutes);
  router.use("/document/reports", documentReportRoutes);

  // Dashboard Graph API's
  router.use("/graph", graphRoutes);

  // Mobile Dashboard
  router.use("/home", dashboardRoutes);

  //   Test DB
  router.get("/company", testDBConnection);
  router.use("/company", companyRouter);

  router.use("/location", locationRoutes);

  router.use("/bull-queue", bullMQRoutes);

  router.use("/notification/count", authenticate, getNotificationCount);
  // router.use("/save-fcm-token",  authenticate ,saveFCMToken);
  router.use("/notification", notificationRouter);
  router.use("/allotment", employeeAllotment);
  router.use("/report", pdfReport);
 

  return router;
};

export default appRoutes;
