import express from "express";
import userRouter from "./usersRoutes.js";
import authRouter from "./authRoutes.js";
import commonRouter from "./commonRoutes.js";
import cottonRouter from "./cottonRoutes.js";
import yarnRouter from "./yarnRoutes.js";
import storesRouter from "./storesRoutes.js";
import hrmRouter from "./hrmRoutes.js";
import gateRouter from "./gateRoutes.js";
import financeRouter from "./financeRoutes.js";
import wasteRouter from "./wasteRoutes.js";
import mechanicalRouter from "./mehanicalRoutes.js";
import cottonOverviewRouter from "./cottonOverviewRoutes.js";
import yarnOverviewRouter from "./yarnOverviewRoutes.js";
import storeOverviewRouter from "./storeOverviewRoutes.js";
import hrmOverviewRouter from "./hrmOverviewRoutes.js";
import gateOverviewRouter from "./gateOverviewRoutes.js";
import financeOverviewRouter from "./financeOverviewRoutes.js";
import cottonReportRoutes from "./cottonReportRoutes.js";
import yarnReportRoutes from "./yarnReportRoutes.js";
import storeReportRoutes from "./storeReportRoutes.js";
import hrmReportRoutes from "./hrmReportRoutes.js";
import payrollReportRoutes from "./payrollReportRoutes.js";
import productionReportRoutes from "./productionReportRoutes.js";
import wasteReportRoutes from "./wasteReportRoutes.js";
import mechanicalReportRoutes from "./mechanicalReportRoutes.js";
import electricalReportRoutes from "./electricalReportRoutes.js";
import weighbridgeReportRoutes from "./weighbridgeReportRoutes.js";
import costingReportRoutes from "./costingReportRoutes.js";
import documentReportRoutes from "./documentReportRoutes.js";
import graphRoutes from "./graphRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import locationRoutes from "./loginLogsRoutes.js";
import { testDBConnection } from "../controllers/testController.js";
import bullMQRoutes from "../routes/bullMQRoutes.js";
import {
  getNotificationCount,
  notificationUpdate,
  saveFCMToken,
} from "../controllers/notifications.comtroller.js";
import { authenticate } from "../middleware/authMiddleware.js";
import notificationRouter from "./notificationRoutes.js";
import employeeAllotment from "./employeeAllotmentRoutes.js";
import pdfReport from "./pdfReportRoutes.js";
import bankRouter from "./bankRoutes.js";
import maintenanceGroupRouter from "./maintenanceGroupRoutes.js";
import departmentGroupRouter from "./departmentGroupRoutes.js";
import departmentRouter from "./departmentRoutes.js";
import companyRouter from "./companyRoutes.js";
import approvalRouter from "./approvalRoutes.js";
import costHeadRouter from "./costHeadRoutes.js";
import stateRouter from "./stateRoutes.js";
import godownRouter from "./godownRoutes.js";
import districtRouter from "./districtRoutes.js";
import costingMasterRouter from "./costingMasterRoutes.js";
import itemCategoryRouter from "./itemCategoryRoutes.js";
import taxRouter from "./taxRoutes.js";
import itemUomRouter from "./itemUomRoutes.js";
import itemUsageTypeRouter from "./itemUsageTypeRoutes.js";
import itemGroupRouter from "./itemGroupRoutes.js";
import itemRouter from "./itemRoutes.js";
import machineRouter from "./machineRoutes.js";
import machineMakeRouter from "./machineMakeRoutes.js";
import machineTypeRouter from "./machineTypeRoutes.js";
import vehicleMakeRouter from "./vehicleMakeRoutes.js";
import vehicleCapacityRouter from "./vehicleCapacityRoutes.js";
import vehicleRouter from "./vehicleRoutes.js";
import agentRouter from "./agentRoutes.js";
import customerApproveRouter from "./customerApproveRoutes.js";
import customerRouter from "./customerRoutes.js";
import customerTypeRouter from "./customerTypeRoutes.js";
import supplierApproveRouter from "./supplierApproveRoutes.js";
import supplierRouter from "./supplierRoutes.js";
import transporterRouter from "./transporterRoutes.js";
import rawMaterialTypeRouter from "./rawMaterialTypeRoutes.js";
import rawMaterialRouter from "./rawMaterialRoutes.js";
import cottonCountRouter from "./cottonCountRoutes.js";
import countGroupRouter from "./countGroupRoutes.js";
import cottonPackingMaterialRouter from "./cottonPackingMaterialRoutes.js";
import stationRouter from "./stationRoutes.js";
import cqtParameterRouter from "./cqtParameterRoutes.js";
import cqtStdRouter from "./cqtStdRoutes.js";
import serviceOrderExpensesRouter from "./serviceOrderExpensesRoutes.js";
import commonServiceActivityRouter from "./commonServiceActivityRoutes.js";
import machineServiceScheduleRouter from "./machineServiceScheduleRoutes.js";
import serviceActivityRouter from "./serviceActivityRoutes.js";
import typeOfBreakdownRouter from "./typeOfBreakdownRoutes.js";
import roleMenuRouter from "./roleMenuRoutes.js";
import einvoiceRouter from "./einvoiceRoutes.js";
import goodsInOutTypeRouter from "./goodsInOutTypeRoutes.js";
import materialTypeRouter from "./materialTypeRoutes.js";
import wasteItemGroupRouter from "./wasteItemGroupRoutes.js";
import wasteItemRouter from "./wasteItemRoutes.js";
import usableWasteItemRouter from "./usableWasteItemRoutes.js";
import wasteProductionRouter from "./wasteProductionRoutes.js";
import usableWasteProductionRouter from "./usableWasteProductionRoutes.js";
import usableWasteIssueRouter from "./usableWasteIssueRoutes.js";
import wasteDCRouter from "./wasteDCRoutes.js";
import wasteInvoiceRouter from "./wasteInvoiceRoutes.js";
import wasteInvoiceApprovalRouter from "./wasteInvoiceApprovalRoutes.js";
import scrapInvoiceRouter from "./scrapInvoiceRoutes.js";
import accountGroupRouter from "./accountGroupRoutes.js";
import cottonPurchaseOrderRouter from "./cottonPurchaseOrderRoutes.js";
import cottonPurchaseOrderAmendmentRouter from "./cottonPurchaseOrderAmendmentRoutes.js";
import cottonPurchaseOrderCancelRouter from "./cottonPurchaseOrderCancelRoutes.js";
import cottonQualityTestApprovalRouter from "./cottonQualityTestApprovalRoutes.js";
import cottonGodownTransferRouter from "./cottonGodownTransferRoutes.js";
import cottonArrivalRouter from "./cottonArrivalRoutes.js";
import cottonWeighmentRouter from "./cottonWeighmentRoutes.js";
import cottonWeighmentApprovalRouter from "./cottonWeighmentApprovalRoutes.js";
import cottonQualityTestRouter from "./cottonQualityTestRoutes.js";
import cottonLotApprovalRouter from "./cottonLotApprovalRoutes.js";
import cottonMixingIssueRequisitionRouter from "./cottonMixingIssueRequisitionRoutes.js";
import cottonIssueRouter from "./cottonIssueRoutes.js";
import cottonSalesRouter from "./cottonSalesRoutes.js";
import cottonSalesReturnRouter from "./cottonSalesReturnRoutes.js";
import cottonRejectRouter from "./cottonRejectRoutes.js";
import cottonRejectLotPendingRouter from "./cottonRejectLotPendingRoutes.js";
import cottonAllowanceRouter from "./cottonAllowanceRoutes.js";
import cottonWeightApprovalRouter from "./cottonWeightApprovalRoutes.js";
import itemRequisitionRouter from "./itemRequisitionRoutes.js";
import itemRequisitionAdjustmentRouter from "./itemRequisitionAdjustmentRoutes.js";
import itemIndentRouter from "./itemIndentRoutes.js";
import purchaseOrderRouter from "./purchaseOrderRoutes.js";
import gstRouter from "./gstRoutes.js";

const router = express.Router();

const appRoutes = () => {
  router.use("/user", userRouter);
  router.use("/auth", authRouter);
  router.use("/badge", commonRouter);
  router.use("/cotton", cottonRouter);
  router.use("/cotton/overview", cottonOverviewRouter);
  router.use("/yarn", yarnRouter);
  router.use("/yarn/overview", yarnOverviewRouter);
  router.use("/stores", storesRouter);
  router.use("/stores/overview", storeOverviewRouter);
  router.use("/hrm", hrmRouter);
  router.use("/hrm/overview", hrmOverviewRouter);
  router.use("/gate", gateRouter);
  router.use("/gate/overview", gateOverviewRouter);
  router.use("/finance", financeRouter);
  router.use("/finance/overview", financeOverviewRouter);
  router.use("/bank", bankRouter);
  router.use("/maintenance-group", maintenanceGroupRouter);
  router.use("/department-group", departmentGroupRouter);
  router.use("/department", departmentRouter);
  router.use("/approval", approvalRouter);
  router.use("/cost-head", costHeadRouter);
  router.use("/state", stateRouter);
  router.use("/godown", godownRouter);
  router.use("/district", districtRouter);
  router.use("/costing-master", costingMasterRouter);
  router.use("/item-category", itemCategoryRouter);
  router.use("/tax", taxRouter);
  router.use("/item-uom", itemUomRouter);
  router.use("/item-usage-type", itemUsageTypeRouter);
  router.use("/item-group", itemGroupRouter);
  router.use("/item", itemRouter);
  router.use("/machine", machineRouter);
  router.use("/machine-make", machineMakeRouter);
  router.use("/machine-type", machineTypeRouter);
  router.use("/vehicle-make", vehicleMakeRouter);
  router.use("/vehicle-capacity", vehicleCapacityRouter);
  router.use("/vehicle", vehicleRouter);
  router.use("/agent", agentRouter);
  router.use("/customer-approve", customerApproveRouter);
  router.use("/customer", customerRouter);
  router.use("/customer-type", customerTypeRouter);
  router.use("/supplier-approve", supplierApproveRouter);
  router.use("/supplier", supplierRouter);
  router.use("/transporter", transporterRouter);
  router.use("/raw-material-type", rawMaterialTypeRouter);
  router.use("/raw-material", rawMaterialRouter);
  router.use("/cotton-count", cottonCountRouter);
  router.use("/count-group", countGroupRouter);
  router.use("/cotton-packing-material", cottonPackingMaterialRouter);
  router.use("/station", stationRouter);
  router.use("/cqt-parameter", cqtParameterRouter);
  router.use("/cqt-std", cqtStdRouter);
  router.use("/goods-in-out-type", goodsInOutTypeRouter);
  router.use("/material-type", materialTypeRouter);
  router.use("/waste-item-group", wasteItemGroupRouter);
  router.use("/waste-item", wasteItemRouter);
  router.use("/usable-waste-item", usableWasteItemRouter);
  router.use("/waste-production", wasteProductionRouter);
  router.use("/usable-waste-production", usableWasteProductionRouter);
  router.use("/usable-waste-issue", usableWasteIssueRouter);
  router.use("/waste-dc", wasteDCRouter);
  router.use("/waste-invoice", wasteInvoiceRouter);
  router.use("/waste-invoice-approval", wasteInvoiceApprovalRouter);
  router.use("/scrap-invoice", scrapInvoiceRouter);
  router.use("/account-group", accountGroupRouter);
  router.use("/cotton-purchase-order", cottonPurchaseOrderRouter);
  router.use("/cotton-purchase-order-amendment", cottonPurchaseOrderAmendmentRouter);
  router.use("/cotton-purchase-order-cancel", cottonPurchaseOrderCancelRouter);
  router.use("/cotton-quality-test-approval", cottonQualityTestApprovalRouter);
  router.use("/cotton-godown-transfer", cottonGodownTransferRouter);
  router.use("/cotton-arrival", cottonArrivalRouter);
  router.use("/cotton-weighment", cottonWeighmentRouter);
  router.use("/cotton-weighment-approval", cottonWeighmentApprovalRouter);
  router.use("/cotton-quality-test", cottonQualityTestRouter);
  router.use("/cotton-lot-approval", cottonLotApprovalRouter);
  router.use("/cotton-mixing-issue-requisition", cottonMixingIssueRequisitionRouter);
  router.use("/cotton-issue", cottonIssueRouter);
  router.use("/cotton-sales", cottonSalesRouter);
  router.use("/cotton-sales-return", cottonSalesReturnRouter);
  router.use("/cotton-reject", cottonRejectRouter);
  router.use("/cotton-reject-lot-pending", cottonRejectLotPendingRouter);
  router.use("/cotton-allowance", cottonAllowanceRouter);
  router.use("/cotton-weight-approval", cottonWeightApprovalRouter);
  router.use("/item-requisition", itemRequisitionRouter);
  router.use("/item-requisition-adjustment", itemRequisitionAdjustmentRouter);
  router.use("/item-indent", itemIndentRouter);
  router.use("/purchase-order", purchaseOrderRouter);
  router.use("/gst", gstRouter);
  router.use("/service-order-expenses", serviceOrderExpensesRouter);
  router.use("/common-service-activity", commonServiceActivityRouter);
  router.use("/machine-service-schedule", machineServiceScheduleRouter);
  router.use("/service-activity", serviceActivityRouter);
  router.use("/type-of-breakdown", typeOfBreakdownRouter);
  router.use("/mechanical", mechanicalRouter);
  router.use("/role-access", roleMenuRouter);
  router.use("/einvoice", einvoiceRouter);

  //REPORTS
  router.use("/cotton/reports", cottonReportRoutes);
  router.use("/yarn/reports", yarnReportRoutes);
  router.use("/store/reports", storeReportRoutes);
  router.use("/hrm/reports", hrmReportRoutes);
  router.use("/payroll/reports", payrollReportRoutes);
  router.use("/production/reports", productionReportRoutes);
  router.use("/waste/reports", wasteReportRoutes);
  router.use("/mechanical/reports", mechanicalReportRoutes);
  router.use("/electrical/reports", electricalReportRoutes);
  router.use("/weighbridge/reports", weighbridgeReportRoutes);
  router.use("/costing/reports", costingReportRoutes);
  router.use("/document/reports", documentReportRoutes);

  // Dashboard Graph API's
  router.use("/graph", graphRoutes);

  // Mobile Dashboard
  router.use("/home", dashboardRoutes);

  //   Test DB
  router.get("/company", testDBConnection);
  router.use("/company", companyRouter);

  router.use("/location", locationRoutes);

  router.use("/bull-queue", bullMQRoutes);

  router.use("/notification/count", authenticate, getNotificationCount);
  // router.use("/save-fcm-token",  authenticate ,saveFCMToken);
  router.use("/notification", notificationRouter);
  router.use("/allotment", employeeAllotment);
  router.use("/report", pdfReport);
 

  return router;
};

export default appRoutes;
