/* =====================================================================
   Role-based menu access — schema, seed, and super-admin bootstrap.
   (Textile ERP — auto-generated menu catalog. Regenerate with
    scratchpad/gen-menu-seed.cjs if the employee menu/modules change.)

   Run ONCE per client database (the same DB your subDBName resolves to).
   Safe to re-run: every step is guarded / upserted.

   Tables:
     tbl_web_Role     - roles (Manager, Employee, ...). IsSuperAdmin set ONLY here.
     tbl_web_Menu     - catalog of access-controlled menus (seeded below).
     tbl_web_RoleMenu - which menus each role can access.
     tbl_web_UserRole - which role each user has (one role per user).
     tbl_web_UserMenu - menus assigned directly to a user (overrides role).

   MenuKey values MUST match the web app:
     - module keys  -> Textiles_ERP/src/access/modules.config.js  (MODULES)
     - screen keys  -> Textiles_ERP/src/modules/employee/menu/menuData.js (form)
   ===================================================================== */

SET NOCOUNT ON;

/* -------------------------- tbl_web_Role ---------------------------- */
IF OBJECT_ID('dbo.tbl_web_Role', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.tbl_web_Role (
    RoleCode     INT IDENTITY(1,1) PRIMARY KEY,
    RoleName     NVARCHAR(100) NOT NULL,
    IsSuperAdmin BIT          NOT NULL CONSTRAINT DF_webRole_IsSuperAdmin DEFAULT (0),
    Status       BIT          NOT NULL CONSTRAINT DF_webRole_Status       DEFAULT (1),
    CompanyCode  INT          NULL,
    CreatedBy    INT          NULL,
    CreatedOn    DATETIME     NOT NULL CONSTRAINT DF_webRole_CreatedOn    DEFAULT (GETDATE()),
    ModifiedBy   INT          NULL,
    ModifiedOn   DATETIME     NULL
  );
END
GO

/* -------------------------- tbl_web_Menu ---------------------------- */
IF OBJECT_ID('dbo.tbl_web_Menu', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.tbl_web_Menu (
    MenuCode  INT IDENTITY(1,1) PRIMARY KEY,
    MenuKey   NVARCHAR(120) NOT NULL,
    MenuLabel NVARCHAR(200) NOT NULL,
    MenuType  NVARCHAR(20)  NOT NULL,   -- module | screen
    GroupName NVARCHAR(120) NULL,
    SortOrder INT           NOT NULL CONSTRAINT DF_webMenu_SortOrder DEFAULT (0),
    Status    BIT           NOT NULL CONSTRAINT DF_webMenu_Status    DEFAULT (1),
    CONSTRAINT UQ_webMenu_MenuKey UNIQUE (MenuKey)
  );
END
GO

/* ------------------------ tbl_web_RoleMenu -------------------------- */
IF OBJECT_ID('dbo.tbl_web_RoleMenu', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.tbl_web_RoleMenu (
    RoleMenuCode INT IDENTITY(1,1) PRIMARY KEY,
    RoleCode     INT NOT NULL,
    MenuCode     INT NOT NULL,
    CONSTRAINT UQ_webRoleMenu UNIQUE (RoleCode, MenuCode),
    CONSTRAINT FK_webRoleMenu_Role FOREIGN KEY (RoleCode) REFERENCES dbo.tbl_web_Role(RoleCode),
    CONSTRAINT FK_webRoleMenu_Menu FOREIGN KEY (MenuCode) REFERENCES dbo.tbl_web_Menu(MenuCode)
  );
END
GO

/* ------------------------ tbl_web_UserRole -------------------------- */
IF OBJECT_ID('dbo.tbl_web_UserRole', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.tbl_web_UserRole (
    UserRoleCode INT IDENTITY(1,1) PRIMARY KEY,
    UserCode     INT NOT NULL,
    RoleCode     INT NOT NULL,
    CONSTRAINT UQ_webUserRole_User UNIQUE (UserCode),
    CONSTRAINT FK_webUserRole_Role FOREIGN KEY (RoleCode) REFERENCES dbo.tbl_web_Role(RoleCode)
  );
END
GO

/* ------------------------ tbl_web_UserMenu -------------------------- *
   Per-user menu assignment, set directly against the UserCode (no role
   lookup). When a user has rows here they OVERRIDE the role's menus in
   /role-access/my-menus; with no rows the user falls back to role menus. */
IF OBJECT_ID('dbo.tbl_web_UserMenu', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.tbl_web_UserMenu (
    UserMenuCode INT IDENTITY(1,1) PRIMARY KEY,
    UserCode     INT NOT NULL,
    MenuCode     INT NOT NULL,
    CONSTRAINT UQ_webUserMenu UNIQUE (UserCode, MenuCode),
    CONSTRAINT FK_webUserMenu_Menu FOREIGN KEY (MenuCode) REFERENCES dbo.tbl_web_Menu(MenuCode)
  );
END
GO

/* --- Per-menu Add / Edit / Delete action flags (added 2026-06-30) --------- *
   Each role->menu and user->menu grant also carries whether that role/user may
   Add / Edit / Delete on the screen. Default 1 (allowed) so existing grants keep
   full CRUD. Idempotent — safe to re-run on an already-deployed database.        */
IF COL_LENGTH('dbo.tbl_web_RoleMenu', 'CanAdd') IS NULL
  ALTER TABLE dbo.tbl_web_RoleMenu ADD CanAdd BIT NOT NULL CONSTRAINT DF_webRoleMenu_CanAdd DEFAULT (1);
IF COL_LENGTH('dbo.tbl_web_RoleMenu', 'CanEdit') IS NULL
  ALTER TABLE dbo.tbl_web_RoleMenu ADD CanEdit BIT NOT NULL CONSTRAINT DF_webRoleMenu_CanEdit DEFAULT (1);
IF COL_LENGTH('dbo.tbl_web_RoleMenu', 'CanDelete') IS NULL
  ALTER TABLE dbo.tbl_web_RoleMenu ADD CanDelete BIT NOT NULL CONSTRAINT DF_webRoleMenu_CanDelete DEFAULT (1);
GO
IF COL_LENGTH('dbo.tbl_web_UserMenu', 'CanAdd') IS NULL
  ALTER TABLE dbo.tbl_web_UserMenu ADD CanAdd BIT NOT NULL CONSTRAINT DF_webUserMenu_CanAdd DEFAULT (1);
IF COL_LENGTH('dbo.tbl_web_UserMenu', 'CanEdit') IS NULL
  ALTER TABLE dbo.tbl_web_UserMenu ADD CanEdit BIT NOT NULL CONSTRAINT DF_webUserMenu_CanEdit DEFAULT (1);
IF COL_LENGTH('dbo.tbl_web_UserMenu', 'CanDelete') IS NULL
  ALTER TABLE dbo.tbl_web_UserMenu ADD CanDelete BIT NOT NULL CONSTRAINT DF_webUserMenu_CanDelete DEFAULT (1);
GO

/* --------------------- Seed / refresh tbl_web_Menu ----------------- *
   Upsert by MenuKey so labels/order stay current and re-runs are safe.
   17 modules + 645 screens = 662 menus.
   KEEP IN SYNC with modules.config.js (modules) + menuData.js (screens).      */
DECLARE @menu TABLE (MenuKey NVARCHAR(120), MenuLabel NVARCHAR(200), MenuType NVARCHAR(20), GroupName NVARCHAR(120), SortOrder INT);

INSERT INTO @menu (MenuKey, MenuLabel, MenuType, GroupName, SortOrder) VALUES
 ('dashboard','DASHBOARD','module','Modules',1),
 ('notifications','NOTIFICATIONS','module','Modules',2),
 ('cotton','COTTON','module','Modules',3),
 ('yarn','YARN','module','Modules',4),
 ('waste','WASTE','module','Modules',5),
 ('store','STORE','module','Modules',6),
 ('production','PRODUCTION','module','Modules',7),
 ('payroll','PAYROLL','module','Modules',8),
 ('mechanical','MECHANICAL','module','Modules',9),
 ('electrical','ELECTRICAL','module','Modules',10),
 ('gate','GATE ENTRY','module','Modules',11),
 ('allotment','ALLOTMENT','module','Modules',12),
 ('costing','PRE COSTING','module','Modules',13),
 ('finance','FINANCE','module','Modules',14),
 ('approvals','APPROVALS','module','Modules',15),
 ('reports','REPORTS','module','Modules',16),
 ('document','DOCUMENT','module','Modules',17),
 ('frmApproval','Approval','screen','Master',18),
 ('frmApprovalDetails','Approval Details','screen','Master',19),
 ('frmBank','Bank','screen','Master',20),
 ('frmBankDetails','Bank Details','screen','Master',21),
 ('frmCompanyDetails','Company Details','screen','Master',22),
 ('frmCostHead','Cost Head','screen','Master',23),
 ('frmCostHeadDetails','Cost Head Details','screen','Master',24),
 ('frmDepartment','Department','screen','Master',25),
 ('frmDepartmentDetails','Department Details','screen','Master',26),
 ('frmDepartmentGroup','Department Group','screen','Master',27),
 ('frmDepartmentGroupDetails','Department Group Details','screen','Master',28),
 ('frmDistrict','District','screen','Master',29),
 ('frmDistrictDetails','District Details','screen','Master',30),
 ('frmGodown','Godown','screen','Master',31),
 ('frmGodownDetails','Godown Details','screen','Master',32),
 ('frmMaintenanceGroup','Maintenance Group','screen','Master',33),
 ('frmMaintenanceGroupDetails','Maintenance Group Details','screen','Master',34),
 ('frmState','State','screen','Master',35),
 ('frmStateDetails','State Details','screen','Master',36),
 ('frmMachine','Machine','screen','Master',37),
 ('frmMachineDetails','Machine Details','screen','Master',38),
 ('frmMachineMake','Machine Make','screen','Master',39),
 ('frmMachineMakeDetails','Machine Make Details','screen','Master',40),
 ('frmMachineType','Machine Type','screen','Master',41),
 ('frmMachineTypeDetails','Machine Type Details','screen','Master',42),
 ('frmServiceActivity','Service Activity','screen','Maintenance',43),
 ('frmServiceActivityDetails','Service Activity Details','screen','Maintenance',44),
 ('frmCommonServiceActivity','Common Service Activity','screen','Maintenance',45),
 ('frmTypeOfBreakDowns','Type Of Break Downs','screen','Maintenance',46),
 ('frmTypeOfBreakDownsDetails','Type Of Break Downs Details','screen','Maintenance',47),
 ('frmAC_Group','AC Group','screen','Finance',48),
 ('frmAccGroupDetails','Acc Group Details','screen','Finance',49),
 ('frmCostingMaster','Costing Master','screen','Master',50),
 ('frmCottonCount','Cotton Count','screen','Cotton',51),
 ('frmCottonCountDetails','Cotton Count Details','screen','Cotton',52),
 ('frmCQTParameter','CQTParameter','screen','Cotton',53),
 ('frmCQTParameterDetails','CQTParameter Details','screen','Cotton',54),
 ('frmCottonQualityTestSTD','Cotton Quality Test STD','screen','Cotton',55),
 ('frmCottonQualityTestSTDPrint','Cotton Quality Test STDPrint','screen','Cotton',56),
 ('frmStation','Station','screen','Cotton',57),
 ('frmStationDetails','Station Details','screen','Cotton',58),
 ('frmCreditType','Credit Type','screen','Finance',59),
 ('frmCreditTypeDetails','Credit Type Details','screen','Finance',60),
 ('frmDebitType','Debit Type','screen','Finance',61),
 ('frmDebitTypeDetails','Debit Type Details','screen','Finance',62),
 ('frmMaterialType','Material Type','screen','Gate Entry',63),
 ('frmMaterialTypeDetails','Material Type Details','screen','Gate Entry',64),
 ('frmLoadUnload_Master','Load Unload Master','screen','Master',65),
 ('frmGoodsInOutType','Goods In Out Type','screen','Gate Entry',66),
 ('frmGoodsInOutTypeDetails','Goods In Out Type Details','screen','Gate Entry',67),
 ('frmHead','Head','screen','Finance',68),
 ('frmHeadDetails','Head Details','screen','Finance',69),
 ('frmRawMaterial','Raw Material','screen','Cotton',70),
 ('frmRawMaterialDetails','Raw Material Details','screen','Cotton',71),
 ('frmRawMaterialType','Raw Material Type','screen','Cotton',72),
 ('frmRawMaterialTypeDetails','Raw Material Type Details','screen','Cotton',73),
 ('frmServiceOrderExpenses','Service Order Expenses','screen','Master',74),
 ('frmServiceOrderExpensesDetails','Service Order Expenses Details','screen','Master',75),
 ('frmTax','Tax','screen','Master',76),
 ('frmTaxDetails','Tax Details','screen','Master',77),
 ('frmAgent','Agent','screen','Master',78),
 ('frmCustomerApprovedDetails','Customer Approved Details','screen','Master',79),
 ('frmCustomerApprovedDetailsEdit','Customer Approved Details Edit','screen','Master',80),
 ('frmCustomer','Customer','screen','Master',81),
 ('frmCustomerDetails','Customer Details','screen','Master',82),
 ('frmCustomerType','Customer Type','screen','Master',83),
 ('frmCustomerTypeDetails','Customer Type Details','screen','Master',84),
 ('frmSupplierApprovalDetails','Supplier Approval Details','screen','Master',85),
 ('frmSupplier','Supplier','screen','Master',86),
 ('frmSupplierDetails','Supplier Details','screen','Master',87),
 ('frmTransporter','Transporter','screen','Master',88),
 ('frmTransporterDetails','Transporter Details','screen','Master',89),
 ('frmItemCategory','Item Category','screen','Stores',90),
 ('frmItemCategoryDetails','Item Category Details','screen','Stores',91),
 ('frmItem','Item','screen','Stores',92),
 ('frmItemUsageType','Item Usage Type','screen','Stores',93),
 ('frmItemUom','Item Uom','screen','Stores',94),
 ('frmItemUomDetails','Item Uom Details','screen','Stores',95),
 ('frmItemGroup','Item Group','screen','Stores',96),
 ('frmItemGroupDetails','Item Group Details','screen','Stores',97),
 ('frmVehicle','Vehicle','screen','Master',98),
 ('frmVehicleDetails','Vehicle Details','screen','Master',99),
 ('frmCottonPurchaseOrder','Cotton Purchase Order','screen','Cotton',100),
 ('frmCottonPurchaseOrderApproval','Cotton Purchase Order Approval','screen','Cotton',101),
 ('frmCottonPurchaseOrderPrint','Cotton Purchase Order Print','screen','Cotton',102),
 ('frmCottonPurchaseOrderCancel','Cotton Purchase Order Cancel','screen','Cotton',103),
 ('frmCottonPurchaseOrder_Amendment','Cotton Purchase Order Amendment','screen','Cotton',104),
 ('frmCottonArrival','Cotton Arrival','screen','Cotton',105),
 ('rptCottonGRN','Cotton GRN','screen','Cotton',106),
 ('frmCottonWeighment','Cotton Weighment','screen','Cotton',107),
 ('frmCottonLabelPrint','Cotton Label Print','screen','Cotton',108),
 ('frmCottonTest','Cotton Test','screen','Cotton',109),
 ('rptCottonSlip','Cotton Slip','screen','Cotton',110),
 ('frmCottonTestApproval','Cotton Test Approval','screen','Cotton',111),
 ('frmCottonLotApproval','Cotton Lot Approval','screen','Cotton',112),
 ('frmCottonLotApprovalDetails','Cotton Lot Approval Details','screen','Cotton',113),
 ('frmCottonMixingIssue_Requisition_New','Cotton Mixing Issue Requisition New','screen','Cotton',114),
 ('rptCottonMixingIssueDetails_Requisition','Cotton Mixing Issue Details Requisition','screen','Cotton',115),
 ('rptCottonMixingIssueRequisitionPrint','Cotton Mixing Issue Requisition Print','screen','Cotton',116),
 ('frmCottonIssue','Cotton Issue','screen','Cotton',117),
 ('frmCottonGodownTransfer','Cotton Godown Transfer','screen','Cotton',118),
 ('frmCottonSales','Cotton Sales','screen','Cotton',119),
 ('frmCottonSalesPrint','Cotton Sales Print','screen','Cotton',120),
 ('frmCottonSalesReturn','Cotton Sales Return','screen','Cotton',121),
 ('frmCottonReject','Cotton Reject','screen','Cotton',122),
 ('frmCottonRejectLotPending','Cotton Reject Lot Pending','screen','Cotton',123),
 ('frmCottonAllowance','Cotton Allowance','screen','Cotton',124),
 ('frmCottonPayment_WeightApproval','Cotton Payment Weight Approval','screen','Cotton',125),
 ('frmCottonBillPassing','Cotton Bill Passing','screen','Cotton',126),
 ('frmCottonBillPassingPrint','Cotton Bill Passing Print','screen','Cotton',127),
 ('rptCottonAllowanceDetails','Cotton Allowance Details','screen','Cotton',128),
 ('rptCottonArrivalDetails','Cotton Arrival Details','screen','Cotton',129),
 ('rptCottonBillPassing','Cotton Bill Passing','screen','Cotton',130),
 ('rptCottonFormIV','Cotton Form IV','screen','Cotton',131),
 ('rptCottonIssueDetails','Cotton Issue Details','screen','Cotton',132),
 ('rptCottonLotApprovalDateWise','Cotton Lot Approval Date Wise','screen','Cotton',133),
 ('rptCottonPurchaseOrderApprovalDateWise','Cotton Purchase Order Approval Date Wise','screen','Cotton',134),
 ('rptCottonPurchaseOrderApprovalPendings','Cotton Purchase Order Approval Pendings','screen','Cotton',135),
 ('rptCottonPurchaseOrderDetails','Cotton Purchase Order Details','screen','Cotton',136),
 ('rptCottonRejectedDetails','Cotton Rejected Details','screen','Cotton',137),
 ('rptCottonWeighmentDetails','Cotton Weighment Details','screen','Cotton',138),
 ('rptCottonLotWear','Cotton Lot Wear','screen','Cotton',139),
 ('rptCottonSalesDetails','Cotton Sales Details','screen','Cotton',140),
 ('rptCottonQualityDetails','Cotton Quality Details','screen','Cotton',141),
 ('rptCottonQualityApprovalPendings','Cotton Quality Approval Pendings','screen','Cotton',142),
 ('frmMixingName','Mixing Name','screen','Production',143),
 ('frmMixingNameDetails','Mixing Name Details','screen','Production',144),
 ('frmStoppageGroup','Stoppage Group','screen','Production',145),
 ('frmStoppageReason','Stoppage Reason','screen','Production',146),
 ('frmStoppageReasonDetails','Stoppage Reason Details','screen','Production',147),
 ('frmCardingMachineSetting','Carding Machine Setting','screen','Production',148),
 ('frmCardingMachineSettingDetails','Carding Machine Setting Details','screen','Production',149),
 ('frmCardingProduction_New','Carding Production New','screen','Production',150),
 ('frmCardingProduction_NewDetails','Carding Production New Details','screen','Production',151),
 ('frmDrawingMachineSetting','Drawing Machine Setting','screen','Production',152),
 ('frmDrawingMachineSettingDetails','Drawing Machine Setting Details','screen','Production',153),
 ('frmDrawingProduction_New','Drawing Production New','screen','Production',154),
 ('frmDrawingProduction_NewDetails','Drawing Production New Details','screen','Production',155),
 ('frmUnilapMachineSetting','Unilap Machine Setting','screen','Production',156),
 ('frmUnilapMachineSettingDetails','Unilap Machine Setting Details','screen','Production',157),
 ('frmUnilapProduction','Unilap Production','screen','Production',158),
 ('frmUnilapProductionDetails','Unilap Production Details','screen','Production',159),
 ('frmComberMachineSetting','Comber Machine Setting','screen','Production',160),
 ('frmComberMachineSettingDetails','Comber Machine Setting Details','screen','Production',161),
 ('frmComberProduction_New','Comber Production New','screen','Production',162),
 ('frmComberProductionDetails','Comber Production Details','screen','Production',163),
 ('frmFinisherDrawingMachineSetting','Finisher Drawing Machine Setting','screen','Production',164),
 ('frmFinisherDrawingProduction','Finisher Drawing Production','screen','Production',165),
 ('frmFinisherDrawingProductionDetails','Finisher Drawing Production Details','screen','Production',166),
 ('frmSimplexMachineSetting','Simplex Machine Setting','screen','Production',167),
 ('frmSimplexMachineSettingDetails','Simplex Machine Setting Details','screen','Production',168),
 ('frmSimplexProduction_New','Simplex Production New','screen','Production',169),
 ('frmSimplexProductionDetails','Simplex Production Details','screen','Production',170),
 ('frmSpinningCountSetting','Spinning Count Setting','screen','Production',171),
 ('frmSpinningCountSettingDetails','Spinning Count Setting Details','screen','Production',172),
 ('frmSpinningFrameSetting','Spinning Frame Setting','screen','Production',173),
 ('frmSpinningProduction_New','Spinning Production New','screen','Production',174),
 ('frmSpinningProductionDetails_New','Spinning Production Details New','screen','Production',175),
 ('frmSpinningStopReason','Spinning Stop Reason','screen','Production',176),
 ('frmSpinningStopReasonDetails','Spinning Stop Reason Details','screen','Production',177),
 ('frmAutoconerCountSetting','Autoconer Count Setting','screen','Production',178),
 ('frmAutoconerCountSettingDetails','Autoconer Count Setting Details','screen','Production',179),
 ('frmAutoconerMachineSetting','Autoconer Machine Setting','screen','Production',180),
 ('frmAutoconerMachineSettingDetails','Autoconer Machine Setting Details','screen','Production',181),
 ('frmAutoconerProduction_New','Autoconer Production New','screen','Production',182),
 ('frmAutoconerProductionDetails','Autoconer Production Details','screen','Production',183),
 ('frmAutoConerCountWiseProduction','Auto Coner Count Wise Production','screen','Production',184),
 ('frmAutoconerCountwiseProductionDetails','Autoconer Countwise Production Details','screen','Production',185),
 ('frmYCPProduction','YCPProduction','screen','Production',186),
 ('frmYCPProductionDetails','YCPProduction Details','screen','Production',187),
 ('frmOECountSetting','OECount Setting','screen','Production',188),
 ('frmOECountSettingDetails','OECount Setting Details','screen','Production',189),
 ('frmOEFrameSetting','OEFrame Setting','screen','Production',190),
 ('frmOEFrameSettingDetails','OEFrame Setting Details','screen','Production',191),
 ('frmOEProduction_New','OEProduction New','screen','Production',192),
 ('frmOEProductionDetails_New','OEProduction Details New','screen','Production',193),
 ('rptCardingProductionDetailReport','Carding Production Detail Report','screen','Production',194),
 ('rptDrawingProductionDetailReport','Drawing Production Detail Report','screen','Production',195),
 ('rptUniLapProductionDetailReport','Uni Lap Production Detail Report','screen','Production',196),
 ('rptComberProductionDetailReport','Comber Production Detail Report','screen','Production',197),
 ('rptFinisherDrawingProductionDetailReport','Finisher Drawing Production Detail Report','screen','Production',198),
 ('rptSimplexProductionDetailReport','Simplex Production Detail Report','screen','Production',199),
 ('rptSpinningProductionDetailReport','Spinning Production Detail Report','screen','Production',200),
 ('rptAutoconerProductionSheet','Autoconer Production Sheet','screen','Production',201),
 ('rptOEProductionDetailReport','OEProduction Detail Report','screen','Production',202),
 ('rptYCPProductionSheet','YCPProduction Sheet','screen','Production',203),
 ('rptProductionOverAllReport','Production Over All Report','screen','Production',204),
 ('rptProductionOverAllReport_AllDepartment','Production Over All Report All Department','screen','Production',205),
 ('rptWaste_OverAll','Waste Over All','screen','Production',206),
 ('frmProductionDataDownload','Production Data Download','screen','Production',207),
 ('frmTestActivity','Test Activity','screen','QC',208),
 ('frmTestActivityDetails','Test Activity Details','screen','QC',209),
 ('frmTestObject','Test Object','screen','QC',210),
 ('frmTestType','Test Type','screen','QC',211),
 ('frmQCTestTransactionParameterMapping','QCTest Transaction Parameter Mapping','screen','QC',212),
 ('frmQCParameterMappingDetails','QCParameter Mapping Details','screen','QC',213),
 ('frmQC','QC','screen','QC',214),
 ('frmQCDetails','QCDetails','screen','QC',215),
 ('frmQCMachineTestEntry','QCMachine Test Entry','screen','QC',216),
 ('frmQCMachineTestEntryDetails','QCMachine Test Entry Details','screen','QC',217),
 ('frmSampleCottonTest','Sample Cotton Test','screen','QC',218),
 ('frmSampleCottonTestDetails','Sample Cotton Test Details','screen','QC',219),
 ('rptSampleCottonQualitySlip','Sample Cotton Quality Slip','screen','QC',220),
 ('frmCottonTestDetails','Cotton Test Details','screen','QC',221),
 ('rptQCCottonTestTransaction','QCCotton Test Transaction','screen','QC',222),
 ('rptSampleCottonQualityTestReport','Sample Cotton Quality Test Report','screen','QC',223),
 ('rptQCMachineTestTransaction','QCMachine Test Transaction','screen','QC',224),
 ('frmCountGroup','Count Group','screen','Yarn Waste',225),
 ('frmCountGroupDetails','Count Group Details','screen','Yarn Waste',226),
 ('frmCountName','Count Name','screen','Yarn Waste',227),
 ('frmCountNameDetails','Count Name Details','screen','Yarn Waste',228),
 ('frmCountType','Count Type','screen','Yarn Waste',229),
 ('frmCountTypeDetails','Count Type Details','screen','Yarn Waste',230),
 ('frmLotNo','Lot No','screen','Yarn Waste',231),
 ('frmLotNoDetails','Lot No Details','screen','Yarn Waste',232),
 ('frmTipColour','Tip Colour','screen','Yarn Waste',233),
 ('frmTipColourDetails','Tip Colour Details','screen','Yarn Waste',234),
 ('frmBagColour','Bag Colour','screen','Yarn Waste',235),
 ('frmBagColourDetails','Bag Colour Details','screen','Yarn Waste',236),
 ('frmSalesType','Sales Type','screen','Yarn Waste',237),
 ('frmSalesTypeDetails','Sales Type Details','screen','Yarn Waste',238),
 ('frmTaxType','Tax Type','screen','Yarn Waste',239),
 ('frmTaxTypeDetails','Tax Type Details','screen','Yarn Waste',240),
 ('frmOtherCharges','Other Charges','screen','Yarn Waste',241),
 ('frmOtherChargesDetails','Other Charges Details','screen','Yarn Waste',242),
 ('frmSalesIncharge','Sales Incharge','screen','Yarn Waste',243),
 ('frmSalesInchargeDetails','Sales Incharge Details','screen','Yarn Waste',244),
 ('frmYarnBagNoGroup','Yarn Bag No Group','screen','Yarn Waste',245),
 ('frmYarnBagNoGroupDetails','Yarn Bag No Group Details','screen','Yarn Waste',246),
 ('frmYarnBagNo_Setting','Yarn Bag No Setting','screen','Yarn Waste',247),
 ('frmYarnBagNo_SettingDetails','Yarn Bag No Setting Details','screen','Yarn Waste',248),
 ('frmBoxPacking','Box Packing','screen','Yarn Waste',249),
 ('frmYarnProductionAdd','Yarn Production Add','screen','Yarn Waste',250),
 ('frmYarnProductionFixing','Yarn Production Fixing','screen','Yarn Waste',251),
 ('frmYarnProductionEntry_OnLine','Yarn Production Entry On Line','screen','Yarn Waste',252),
 ('frmBarcodeLabelPrint','Barcode Label Print','screen','Yarn Waste',253),
 ('frmYarnConeProductionAdd','Yarn Cone Production Add','screen','Yarn Waste',254),
 ('frmSalesOrderAdd','Sales Order Add','screen','Yarn Waste',255),
 ('frmSalesOrderApproval','Sales Order Approval','screen','Yarn Waste',256),
 ('frmSalesOrderPrint','Sales Order Print','screen','Yarn Waste',257),
 ('frmSalesOrderDetails','Sales Order Details','screen','Yarn Waste',258),
 ('frmSalesOrderAdjustment','Sales Order Adjustment','screen','Yarn Waste',259),
 ('frmSalesOrderApprovalCancel','Sales Order Approval Cancel','screen','Yarn Waste',260),
 ('frmInvoiceDelete','Invoice Delete','screen','Yarn Waste',261),
 ('frmInvoiceConfirmation','Invoice Confirmation','screen','Yarn Waste',262),
 ('frmInvoiceDuplicatePrint','Invoice Duplicate Print','screen','Yarn Waste',263),
 ('frmGatePass','Gate Pass','screen','Yarn Waste',264),
 ('frmFullInvoice','Full Invoice','screen','Yarn Waste',265),
 ('frmInvoiceCancel','Invoice Cancel','screen','Yarn Waste',266),
 ('frmPackingAdd_Multi','Packing Add Multi','screen','Yarn Waste',267),
 ('frmDespatchAdviceBagNoPrint','Despatch Advice Bag No Print','screen','Yarn Waste',268),
 ('frmSalesReturn','Sales Return','screen','Yarn Waste',269),
 ('frmSalesReturnDetails','Sales Return Details','screen','Yarn Waste',270),
 ('frmSalesReturnApproval','Sales Return Approval','screen','Yarn Waste',271),
 ('frmSalesReturnPrint','Sales Return Print','screen','Yarn Waste',272),
 ('frmYarnPurchaseOrder','Yarn Purchase Order','screen','Yarn Waste',273),
 ('frmYarnPurchaseOrderDetails','Yarn Purchase Order Details','screen','Yarn Waste',274),
 ('frmYarnPurchaseOrderPrint','Yarn Purchase Order Print','screen','Yarn Waste',275),
 ('frmYarnPurchaseOrderApproval','Yarn Purchase Order Approval','screen','Yarn Waste',276),
 ('frmYarnGRN','Yarn GRN','screen','Yarn Waste',277),
 ('frmYarnGRNDetails','Yarn GRNDetails','screen','Yarn Waste',278),
 ('frmYarnGRNPrint','Yarn GRNPrint','screen','Yarn Waste',279),
 ('frmYarnReceipt','Yarn Receipt','screen','Yarn Waste',280),
 ('frmYarnReceiptDetails','Yarn Receipt Details','screen','Yarn Waste',281),
 ('frmYarnReceiptPrint','Yarn Receipt Print','screen','Yarn Waste',282),
 ('frmYarnIntenalTransfer','Yarn Intenal Transfer','screen','Yarn Waste',283),
 ('frmTransportInvoice','Transport Invoice','screen','Yarn Waste',284),
 ('frmTransportInvoiceDetails','Transport Invoice Details','screen','Yarn Waste',285),
 ('frmTransportInvoicePrint','Transport Invoice Print','screen','Yarn Waste',286),
 ('frmTransportInvoiceApproval','Transport Invoice Approval','screen','Yarn Waste',287),
 ('frmYarnAgentCommission','Yarn Agent Commission','screen','Yarn Waste',288),
 ('frmYarnAgentCommissionDetails','Yarn Agent Commission Details','screen','Yarn Waste',289),
 ('frmYarnAgentCommissionPrint','Yarn Agent Commission Print','screen','Yarn Waste',290),
 ('frmYarnAgentCommission_Change','Yarn Agent Commission Change','screen','Yarn Waste',291),
 ('frmYarnAgentCommissionApproval','Yarn Agent Commission Approval','screen','Yarn Waste',292),
 ('frmProcessStock','Process Stock','screen','Yarn Waste',293),
 ('rptCountName','Count Name','screen','Yarn Waste',294),
 ('rptProduction','Production','screen','Yarn Waste',295),
 ('rptSalesOrderDetailsDateWise','Sales Order Details Date Wise','screen','Yarn Waste',296),
 ('rptPendingDespatchOrder','Pending Despatch Order','screen','Yarn Waste',297),
 ('rptYarnPurchaseOrderDetailsCountTypeWise','Yarn Purchase Order Details Count Type Wise','screen','Yarn Waste',298),
 ('rptYarnGRNDetailsDateWise','Yarn GRNDetails Date Wise','screen','Yarn Waste',299),
 ('rptInvoiceDateWise','Invoice Date Wise','screen','Yarn Waste',300),
 ('rptYarnAgentCommissionDetails','Yarn Agent Commission Details','screen','Yarn Waste',301),
 ('rptTransportInvoiceDetails','Transport Invoice Details','screen','Yarn Waste',302),
 ('rptSalesReturnDetailsDateWise','Sales Return Details Date Wise','screen','Yarn Waste',303),
 ('rptProcessStock_Print','Process Stock Print','screen','Yarn Waste',304),
 ('rptStock_BagStockDetails','Stock Bag Stock Details','screen','Yarn Waste',305),
 ('rptStockStatement_Yarn','Stock Statement Yarn','screen','Yarn Waste',306),
 ('rptYarnGatePass','Yarn Gate Pass','screen','Yarn Waste',307),
 ('rptYarnRG1','Yarn RG1','screen','Yarn Waste',308),
 ('rptYarnInternalTransfer','Yarn Internal Transfer','screen','Yarn Waste',309),
 ('rptSalesDayBookDetails','Sales Day Book Details','screen','Yarn Waste',310),
 ('rptInsuranceDetails','Insurance Details','screen','Yarn Waste',311),
 ('frmWasteItemGroup','Waste Item Group','screen','Waste',312),
 ('frmWasteItemGroupDetails','Waste Item Group Details','screen','Waste',313),
 ('frmWasteItem','Waste Item','screen','Waste',314),
 ('frmWasteItemDetails','Waste Item Details','screen','Waste',315),
 ('frmUsableWasteItem','Usable Waste Item','screen','Waste',316),
 ('frmUsableWasteItemDetails','Usable Waste Item Details','screen','Waste',317),
 ('frmWasteProduction','Waste Production','screen','Waste',318),
 ('frmWasteBarcodeLabelPrint','Waste Barcode Label Print','screen','Waste',319),
 ('frmUsableWasteProduction','Usable Waste Production','screen','Waste',320),
 ('frmUsableWasteProductionDetails','Usable Waste Production Details','screen','Waste',321),
 ('frmUsableWasteItemIssue','Usable Waste Item Issue','screen','Waste',322),
 ('rptUsableWasteItemIssuePrint','Usable Waste Item Issue Print','screen','Waste',323),
 ('frmWasteDC','Waste DC','screen','Waste',324),
 ('rptWasteInvoiceDCPrint','Waste Invoice DCPrint','screen','Waste',325),
 ('frmWasteInvoice','Waste Invoice','screen','Waste',326),
 ('frmWasteInvoiceDetails','Waste Invoice Details','screen','Waste',327),
 ('frmWasteInvoiceApproval','Waste Invoice Approval','screen','Waste',328),
 ('frmWasteInvoicePrint','Waste Invoice Print','screen','Waste',329),
 ('frmScrabInvoice','Scrab Invoice','screen','Waste',330),
 ('frmScrabInvoiceDetails','Scrab Invoice Details','screen','Waste',331),
 ('rptScrapInvoicePrint','Scrap Invoice Print','screen','Waste',332),
 ('frmWasteInvoiceGatePass','Waste Invoice Gate Pass','screen','Waste',333),
 ('frmWasteGatePassPrint','Waste Gate Pass Print','screen','Waste',334),
 ('rptWasteProductionDateWise','Waste Production Date Wise','screen','Waste',335),
 ('rptWasteInvoiceAgentWise','Waste Invoice Agent Wise','screen','Waste',336),
 ('rptWasteStockStatus','Waste Stock Status','screen','Waste',337),
 ('rptWasteStock','Waste Stock','screen','Waste',338),
 ('rptWasteScrapInvoice','Waste Scrap Invoice','screen','Waste',339),
 ('rptUsablewasteProductionDateWise','Usablewaste Production Date Wise','screen','Waste',340),
 ('rptUsableWasteItemIssue','Usable Waste Item Issue','screen','Waste',341),
 ('frmItemRequisition','Item Requisition','screen','Stores',342),
 ('frmItemRequistionApproval','Item Requistion Approval','screen','Stores',343),
 ('frmItemRequisitionPrint','Item Requisition Print','screen','Stores',344),
 ('frmItemIndent','Item Indent','screen','Stores',345),
 ('frmItemRequisitionAdjustment','Item Requisition Adjustment','screen','Stores',346),
 ('frmIssueApproval1','Issue Approval1','screen','Stores',347),
 ('frmIssueApproval2','Issue Approval2','screen','Stores',348),
 ('frmPurchaseEnquiry','Purchase Enquiry','screen','Stores',349),
 ('frmPurchaseEnquiryPrint','Purchase Enquiry Print','screen','Stores',350),
 ('frmPurchaseOrder','Purchase Order','screen','Stores',351),
 ('frmPurchaseOrderDirect','Purchase Order Direct','screen','Stores',352),
 ('rptPODisplay','PODisplay','screen','Stores',353),
 ('frmPurchaseOrderApproval_Stage1','Purchase Order Approval Stage1','screen','Stores',354),
 ('frmPurchaseOrderApproval_Stage2','Purchase Order Approval Stage2','screen','Stores',355),
 ('frmPurchaseOrderApproval_Stage3','Purchase Order Approval Stage3','screen','Stores',356),
 ('frmPurchaseOrderAmendment_New','Purchase Order Amendment New','screen','Stores',357),
 ('frmPurchaseOrder_Amendment_Approval1','Purchase Order Amendment Approval1','screen','Stores',358),
 ('frmPurchaseOrder_Amendment_Approval2','Purchase Order Amendment Approval2','screen','Stores',359),
 ('frmPurchaseReturn','Purchase Return','screen','Stores',360),
 ('frmPurchaseOrder_Close','Purchase Order Close','screen','Stores',361),
 ('frmPurchaseOrderReceivedMultiPO','Purchase Order Received Multi PO','screen','Stores',362),
 ('frmInwardGRNPrint','Inward GRNPrint','screen','Stores',363),
 ('frmStoresGRNApproval','Stores GRNApproval','screen','Stores',364),
 ('frmStoresGRNApproval_Cancel','Stores GRNApproval Cancel','screen','Stores',365),
 ('frmInwardWithOutPO_New','Inward With Out PO New','screen','Stores',366),
 ('frmIssue_New','Issue New','screen','Stores',367),
 ('frmDirectIssue','Direct Issue','screen','Stores',368),
 ('frmStockAdjustment','Stock Adjustment','screen','Stores',369),
 ('frmGoodsInStore','Goods In Store','screen','Stores',370),
 ('frmGoodsOutStore','Goods Out Store','screen','Stores',371),
 ('frmGoodsOutApprovalStage1','Goods Out Approval Stage1','screen','Stores',372),
 ('frmGoodsOutApprovalStage2','Goods Out Approval Stage2','screen','Stores',373),
 ('rptGoodsOutGatePass','Goods Out Gate Pass','screen','Stores',374),
 ('frmServiceOrderRequisition','Service Order Requisition','screen','Stores',375),
 ('frmServiceOrderRequisitionPrint','Service Order Requisition Print','screen','Stores',376),
 ('frmServiceOrderApprovalPending','Service Order Approval Pending','screen','Stores',377),
 ('frmServiceOrderComplete','Service Order Complete','screen','Stores',378),
 ('frmDirectServiceOrderComplete','Direct Service Order Complete','screen','Stores',379),
 ('frmServiceOrderCompleteBillPassing','Service Order Complete Bill Passing','screen','Stores',380),
 ('frmServiceOrderCompletePrint','Service Order Complete Print','screen','Stores',381),
 ('rptItemRequisitionDetails','Item Requisition Details','screen','Stores',382),
 ('rptPurchaseOrderDetails','Purchase Order Details','screen','Stores',383),
 ('rptPurchaseOrderReceivedDetails','Purchase Order Received Details','screen','Stores',384),
 ('rptGRNWithoutIssue','GRNWithout Issue','screen','Stores',385),
 ('rptPurchaseReturnDetails','Purchase Return Details','screen','Stores',386),
 ('rptStoresDailyOverAllReportDetails','Stores Daily Over All Report Details','screen','Stores',387),
 ('rptStoresGRNBillPassingDetails','Stores GRNBill Passing Details','screen','Stores',388),
 ('rptServiceOrderCompleteBillPassingDetails','Service Order Complete Bill Passing Details','screen','Stores',389),
 ('rptGRNApprovalPendingDetails','GRNApproval Pending Details','screen','Stores',390),
 ('rptIssueDetails','Issue Details','screen','Stores',391),
 ('rptIssueReturnDetails','Issue Return Details','screen','Stores',392),
 ('rptGateEntryGoodsOutApprovalPending','Gate Entry Goods Out Approval Pending','screen','Stores',393),
 ('rptGateEntryGoodsOutApprovalPendingStage2','Gate Entry Goods Out Approval Pending Stage2','screen','Stores',394),
 ('rptStockAdjustmentDetails','Stock Adjustment Details','screen','Stores',395),
 ('rptStockLedger','Stock Ledger','screen','Stores',396),
 ('rptStoreCostingDetails','Store Costing Details','screen','Stores',397),
 ('rptServiceOrderRequisitionDetailsDateWise','Service Order Requisition Details Date Wise','screen','Stores',398),
 ('rptServiceOrderRequisitionSupplierWise','Service Order Requisition Supplier Wise','screen','Stores',399),
 ('rptServiceOrderRequisitionDetails','Service Order Requisition Details','screen','Stores',400),
 ('rptServiceOrderCompleteDetailsDateWise','Service Order Complete Details Date Wise','screen','Stores',401),
 ('rptServiceOrderCompleteDetailsSupplierWise','Service Order Complete Details Supplier Wise','screen','Stores',402),
 ('rptServiceOrderCompleteDetailsDepartmentWise','Service Order Complete Details Department Wise','screen','Stores',403),
 ('frmGrade','Grade','screen','Pay Roll',404),
 ('frmGradeDetails','Grade Details','screen','Pay Roll',405),
 ('frmTypeOfEmployment','Type Of Employment','screen','Pay Roll',406),
 ('frmTypeofEmploymentDetails','Typeof Employment Details','screen','Pay Roll',407),
 ('frmPayHead','Pay Head','screen','Pay Roll',408),
 ('frmPayHeadDetails','Pay Head Details','screen','Pay Roll',409),
 ('frmHoliday','Holiday','screen','Pay Roll',410),
 ('frmHolidayDetails','Holiday Details','screen','Pay Roll',411),
 ('frmManualEntryReason','Manual Entry Reason','screen','Pay Roll',412),
 ('frmManualEntryReasonDetails','Manual Entry Reason Details','screen','Pay Roll',413),
 ('frmRoute','Route','screen','Pay Roll',414),
 ('frmRouteDetails','Route Details','screen','Pay Roll',415),
 ('frmRouteVehicle','Route Vehicle','screen','Pay Roll',416),
 ('frmRouteVehicleDetails','Route Vehicle Details','screen','Pay Roll',417),
 ('frmPayPeriod','Pay Period','screen','Pay Roll',418),
 ('frmPayPeriodDetails','Pay Period Details','screen','Pay Roll',419),
 ('frmLabourCommissionCategory','Labour Commission Category','screen','Pay Roll',420),
 ('frmBloodGroup','Blood Group','screen','Pay Roll',421),
 ('frmEmpGroup','Emp Group','screen','Pay Roll',422),
 ('frmEmpCategory','Emp Category','screen','Pay Roll',423),
 ('frmDesignation','Designation','screen','Pay Roll',424),
 ('frmWorkLoad','Work Load','screen','Pay Roll',425),
 ('frmEmployee','Employee','screen','Pay Roll',426),
 ('frmEmployeeShiftGroupChange','Employee Shift Group Change','screen','Pay Roll',427),
 ('frmRoom','Room','screen','Pay Roll',428),
 ('frmEmployeeBatch','Employee Batch','screen','Pay Roll',429),
 ('frmHostelType','Hostel Type','screen','Pay Roll',430),
 ('frmCLOpeningEntry','CLOpening Entry','screen','Pay Roll',431),
 ('frmShiftGroup','Shift Group','screen','Pay Roll',432),
 ('frmShift','Shift','screen','Pay Roll',433),
 ('frmCanteenShift','Canteen Shift','screen','Pay Roll',434),
 ('frmDownloadFromMachine','Download From Machine','screen','Pay Roll',435),
 ('frmImportData','Import Data','screen','Pay Roll',436),
 ('frmGenerateAttendance','Generate Attendance','screen','Pay Roll',437),
 ('frmGenerateAttendanceGOTS','Generate Attendance GOTS','screen','Pay Roll',438),
 ('frmAttenManualEntry','Atten Manual Entry','screen','Pay Roll',439),
 ('frmAttendanceManualEntry','Attendance Manual Entry','screen','Pay Roll',440),
 ('frmOTManualEntry','OTManual Entry','screen','Pay Roll',441),
 ('frmAttendanceApprove','Attendance Approve','screen','Pay Roll',442),
 ('frmAttendanceAttendanceOffLineApproval2','Attendance Attendance Off Line Approval2','screen','Pay Roll',443),
 ('frmAttendanceTransfer','Attendance Transfer','screen','Pay Roll',444),
 ('frmEmployeeAllottment','Employee Allottment','screen','Pay Roll',445),
 ('frmLateHrs','Late Hrs','screen','Pay Roll',446),
 ('frmNewJoinerSalaryApproval','New Joiner Salary Approval','screen','Pay Roll',447),
 ('rptNewJoinerPass','New Joiner Pass','screen','Pay Roll',448),
 ('frmVacationEntry','Vacation Entry','screen','Pay Roll',449),
 ('frmVacationEntryDetails','Vacation Entry Details','screen','Pay Roll',450),
 ('rptVacationEntryDetails','Vacation Entry Details','screen','Pay Roll',451),
 ('frmLeftRejoin','Left Rejoin','screen','Pay Roll',452),
 ('frmLeftRejoinDetails','Left Rejoin Details','screen','Pay Roll',453),
 ('rptRejoinLeftDetails','Rejoin Left Details','screen','Pay Roll',454),
 ('frmIncrement','Increment','screen','Pay Roll',455),
 ('frmIncrement_Bulk','Increment Bulk','screen','Pay Roll',456),
 ('frmIncrementApproveDetails','Increment Approve Details','screen','Pay Roll',457),
 ('frmIncrementApprove_1PendingDetails','Increment Approve 1 Pending Details','screen','Pay Roll',458),
 ('frmOnDutyEntry','On Duty Entry','screen','Pay Roll',459),
 ('frmOnDutyEntryDetails','On Duty Entry Details','screen','Pay Roll',460),
 ('frmOnDutyEntryApproval','On Duty Entry Approval','screen','Pay Roll',461),
 ('frmCompensationWorkEntry','Compensation Work Entry','screen','Pay Roll',462),
 ('frmCompensationworkEntryDetails','Compensationwork Entry Details','screen','Pay Roll',463),
 ('frmCompensationWorkEntryApproval','Compensation Work Entry Approval','screen','Pay Roll',464),
 ('frmPayRollTransection_OverAll','Pay Roll Transection Over All','screen','Pay Roll',465),
 ('frmLoan','Loan','screen','Pay Roll',466),
 ('frmLoanDetails','Loan Details','screen','Pay Roll',467),
 ('frmLoanApprovalDetails','Loan Approval Details','screen','Pay Roll',468),
 ('frmLoanRequestForm','Loan Request Form','screen','Pay Roll',469),
 ('frmLoanClose','Loan Close','screen','Pay Roll',470),
 ('frmLoanCloseDetails','Loan Close Details','screen','Pay Roll',471),
 ('frmLabourAgentCommission','Labour Agent Commission','screen','Pay Roll',472),
 ('frmLabourAgentCommissionDetails','Labour Agent Commission Details','screen','Pay Roll',473),
 ('frmBonusPaid','Bonus Paid','screen','Pay Roll',474),
 ('frmHoldSalary','Hold Salary','screen','Pay Roll',475),
 ('frmSalaryPaymentEntry','Salary Payment Entry','screen','Pay Roll',476),
 ('frmSalaryComplete','Salary Complete','screen','Pay Roll',477),
 ('frmCanteenEmployeeMovementDownload','Canteen Employee Movement Download','screen','Pay Roll',478),
 ('frmEmployeeProfileCheck','Employee Profile Check','screen','Pay Roll',479),
 ('rptEmployeeMaster','Employee Master','screen','Pay Roll',480),
 ('rptDesignationChange','Designation Change','screen','Pay Roll',481),
 ('rptRoomDetails','Room Details','screen','Pay Roll',482),
 ('rptShiftMaster','Shift Master','screen','Pay Roll',483),
 ('rptNewJoinApproval_Report','New Join Approval Report','screen','Pay Roll',484),
 ('rptEmployeeSalaryNotFixed','Employee Salary Not Fixed','screen','Pay Roll',485),
 ('rptEmployeeProfile','Employee Profile','screen','Pay Roll',486),
 ('rptEmployeeIDCard','Employee IDCard','screen','Pay Roll',487),
 ('rptEmployeeServiceCard','Employee Service Card','screen','Pay Roll',488),
 ('rptEmployeeBirthDay','Employee Birth Day','screen','Pay Roll',489),
 ('rptEmployeeJoining','Employee Joining','screen','Pay Roll',490),
 ('rptEmployeeLeft','Employee Left','screen','Pay Roll',491),
 ('rptEmployeeJoinLeft','Employee Join Left','screen','Pay Roll',492),
 ('rptVacationDetails','Vacation Details','screen','Pay Roll',493),
 ('rptRejoinReport','Rejoin Report','screen','Pay Roll',494),
 ('rptEmployeeEngagement','Employee Engagement','screen','Pay Roll',495),
 ('rptLateHrsDetails','Late Hrs Details','screen','Pay Roll',496),
 ('rptEmployeeDetailsNew','Employee Details New','screen','Pay Roll',497),
 ('rptEmployeeAllotment','Employee Allotment','screen','Pay Roll',498),
 ('rptAttendanceCheckList','Attendance Check List','screen','Pay Roll',499),
 ('rptAttendanceDetails','Attendance Details','screen','Pay Roll',500),
 ('rptMovementDetails','Movement Details','screen','Pay Roll',501),
 ('rptAttendanceOverAll','Attendance Over All','screen','Pay Roll',502),
 ('rptLateInDetails','Late In Details','screen','Pay Roll',503),
 ('rptLeaveDetails','Leave Details','screen','Pay Roll',504),
 ('frmAttendanceDetails_GOTS','Attendance Details GOTS','screen','Pay Roll',505),
 ('rptStrengthAbstract','Strength Abstract','screen','Pay Roll',506),
 ('rptCostingAbstract','Costing Abstract','screen','Pay Roll',507),
 ('frmTimeCard','Time Card','screen','Pay Roll',508),
 ('rptMuster','Muster','screen','Pay Roll',509),
 ('rptMusterAll','Muster All','screen','Pay Roll',510),
 ('rptForm25','Form25','screen','Pay Roll',511),
 ('rptEmployeeForm10','Employee Form10','screen','Pay Roll',512),
 ('rptMonthlySalaryDetails','Monthly Salary Details','screen','Pay Roll',513),
 ('rptMonthlySalaryPayHeadDetails','Monthly Salary Pay Head Details','screen','Pay Roll',514),
 ('rptForm15','Form15','screen','Pay Roll',515),
 ('rptPaySlipDetails','Pay Slip Details','screen','Pay Roll',516),
 ('rptLabourAgentCommissionDetails','Labour Agent Commission Details','screen','Pay Roll',517),
 ('rptLabourAgentCommissionReport','Labour Agent Commission Report','screen','Pay Roll',518),
 ('rptCanteenMovementDetails','Canteen Movement Details','screen','Pay Roll',519),
 ('rptBonusDetails','Bonus Details','screen','Pay Roll',520),
 ('rptPaidUnPaid','Paid Un Paid','screen','Pay Roll',521),
 ('rptBonusPaidUnPaid','Bonus Paid Un Paid','screen','Pay Roll',522),
 ('rptEmployeeIncrement','Employee Increment','screen','Pay Roll',523),
 ('rptEmployeeLedger','Employee Ledger','screen','Pay Roll',524),
 ('frmWeighBridge','Weigh Bridge','screen','Weigh Bridge',525),
 ('frmWeighBridgePrint','Weigh Bridge Print','screen','Weigh Bridge',526),
 ('frmWBTest','WBTest','screen','Weigh Bridge',527),
 ('rptWeighDetails','Weigh Details','screen','Weigh Bridge',528),
 ('frmCompanyVisitorsIn','Company Visitors In','screen','Gate Entry',529),
 ('frmCompanyCourier','Company Courier','screen','Gate Entry',530),
 ('frmGoodsInGate','Goods In Gate','screen','Gate Entry',531),
 ('frmGoodsInGatePass','Goods In Gate Pass','screen','Gate Entry',532),
 ('frmGoodsOutGate','Goods Out Gate','screen','Gate Entry',533),
 ('frmGateEntryGoodsOutCancel','Gate Entry Goods Out Cancel','screen','Gate Entry',534),
 ('frmGateEmployeeMovementDownload','Gate Employee Movement Download','screen','Gate Entry',535),
 ('frmParentsVisitorsIn','Parents Visitors In','screen','Gate Entry',536),
 ('frmCompanyVisitorsNameMapping','Company Visitors Name Mapping','screen','Gate Entry',537),
 ('frmVehicleInOut','Vehicle In Out','screen','Gate Entry',538),
 ('rptVechicleInOutPrint','Vechicle In Out Print','screen','Gate Entry',539),
 ('frmVechicleInOutApproval','Vechicle In Out Approval','screen','Gate Entry',540),
 ('rptGateEntryGoodsIn','Gate Entry Goods In','screen','Gate Entry',541),
 ('rptGateEntryGoodsOut','Gate Entry Goods Out','screen','Gate Entry',542),
 ('rptGateEntryReturnableGoods','Gate Entry Returnable Goods','screen','Gate Entry',543),
 ('rptGateEntryReturnableGoodsInOutDetails','Gate Entry Returnable Goods In Out Details','screen','Gate Entry',544),
 ('rptCompanyVisitorsInoutReport','Company Visitors Inout Report','screen','Gate Entry',545),
 ('rptCompanyCourierInOutReport','Company Courier In Out Report','screen','Gate Entry',546),
 ('rptGateEntryVehicleInOut','Gate Entry Vehicle In Out','screen','Gate Entry',547),
 ('rptGateMovementDetails','Gate Movement Details','screen','Gate Entry',548),
 ('rptParentsInoutReport','Parents Inout Report','screen','Gate Entry',549),
 ('frmSchedule','Schedule','screen','Maintenance',550),
 ('frmBreakDown','Break Down','screen','Maintenance',551),
 ('frmWorkOrder','Work Order','screen','Maintenance',552),
 ('frmMachineTapeCut','Machine Tape Cut','screen','Maintenance',553),
 ('frmMaintenanceBuffing','Maintenance Buffing','screen','Maintenance',554),
 ('frmMaintenanceDesignation','Maintenance Designation','screen','Maintenance',555),
 ('frmMaintenanceEmpEngaged','Maintenance Emp Engaged','screen','Maintenance',556),
 ('rptMachineDocumentPrint','Machine Document Print','screen','Maintenance',557),
 ('rptMachineDetails','Machine Details','screen','Maintenance',558),
 ('rptTypeOfBreakDown','Type Of Break Down','screen','Maintenance',559),
 ('rptServiceSchedule','Service Schedule','screen','Maintenance',560),
 ('rptBreakDown','Break Down','screen','Maintenance',561),
 ('rptBreakDownMonthWise','Break Down Month Wise','screen','Maintenance',562),
 ('rptWorkOrderSchedule','Work Order Schedule','screen','Maintenance',563),
 ('rptNextServiceScheduleDetails','Next Service Schedule Details','screen','Maintenance',564),
 ('rptMaintenance_Consumption','Maintenance Consumption','screen','Maintenance',565),
 ('rptMaintenance_LastMaintenanceDate_Consumption','Maintenance Last Maintenance Date Consumption','screen','Maintenance',566),
 ('rptMachineTapeCutDetails','Machine Tape Cut Details','screen','Maintenance',567),
 ('rptMaintenancebuffing','Maintenancebuffing','screen','Maintenance',568),
 ('rptMaintenanceDailyReport','Maintenance Daily Report','screen','Maintenance',569),
 ('frmSolarGroup','Solar Group','screen','Maintenance',570),
 ('frmPlantGroup','Plant Group','screen','Maintenance',571),
 ('frmSolarLocation','Solar Location','screen','Maintenance',572),
 ('frmEBMeterMaster','EBMeter Master','screen','Maintenance',573),
 ('frmPlantMaster','Plant Master','screen','Maintenance',574),
 ('frmSlot','Slot','screen','Maintenance',575),
 ('frmGeneratorMachineGroup','Generator Machine Group','screen','Maintenance',576),
 ('frmPowerCategory','Power Category','screen','Maintenance',577),
 ('frmCompressorGroupMaster','Compressor Group Master','screen','Maintenance',578),
 ('frmMachineGroup','Machine Group','screen','Maintenance',579),
 ('frmEBRate','EBRate','screen','Maintenance',580),
 ('frmElectricalReadingEntry','Electrical Reading Entry','screen','Maintenance',581),
 ('frmEB_PowerFailure','EB Power Failure','screen','Maintenance',582),
 ('rptEBSlotDateWiseReport','EBSlot Date Wise Report','screen','Maintenance',583),
 ('rptCompressorReading','Compressor Reading','screen','Maintenance',584),
 ('rptPowerFailure','Power Failure','screen','Maintenance',585),
 ('rptDieselConsumption','Diesel Consumption','screen','Maintenance',586),
 ('rptPowerConsumption_PowerGroupWise','Power Consumption Power Group Wise','screen','Maintenance',587),
 ('rptEBReadingMonthlyReport','EBReading Monthly Report','screen','Maintenance',588),
 ('rptGeneratorReadingDetails','Generator Reading Details','screen','Maintenance',589),
 ('rptSolarReading','Solar Reading','screen','Maintenance',590),
 ('rptElectricalCheckList','Electrical Check List','screen','Maintenance',591),
 ('rptElectricalDailyReport','Electrical Daily Report','screen','Maintenance',592),
 ('frmVehicleExpensessGroup','Vehicle Expensess Group','screen','Maintenance',593),
 ('frmVehicleExpensess','Vehicle Expensess','screen','Maintenance',594),
 ('frmVehicleExpencessEntry','Vehicle Expencess Entry','screen','Maintenance',595),
 ('frmVoucherType','Voucher Type','screen','Finance',596),
 ('frmVoucherTypeDetails','Voucher Type Details','screen','Finance',597),
 ('frmAC_Group_Details','AC Group Details','screen','Finance',598),
 ('frmAC_Ledger','AC Ledger','screen','Finance',599),
 ('frmAC_LedgerDetails','AC Ledger Details','screen','Finance',600),
 ('frmAC_Journal','AC Journal','screen','Finance',601),
 ('frmAC_JournalDetails','AC Journal Details','screen','Finance',602),
 ('frmAC_Contra','AC Contra','screen','Finance',603),
 ('frmAC_ContraDetails','AC Contra Details','screen','Finance',604),
 ('frmReceipt','Receipt','screen','Finance',605),
 ('frmReceiptDetails','Receipt Details','screen','Finance',606),
 ('rptReceipt','Receipt','screen','Finance',607),
 ('frmReceiptApproval','Receipt Approval','screen','Finance',608),
 ('frmReceiptApproval_Delete','Receipt Approval Delete','screen','Finance',609),
 ('frmReceiptApproval_Final','Receipt Approval Final','screen','Finance',610),
 ('frmReceiptApproval_Final_Delete','Receipt Approval Final Delete','screen','Finance',611),
 ('frmAdvanceRequisition','Advance Requisition','screen','Finance',612),
 ('frmAdvanceRequisitionDetails','Advance Requisition Details','screen','Finance',613),
 ('frmAdvanceRequisitionPrint','Advance Requisition Print','screen','Finance',614),
 ('frmAdvancePaymentRequisitionApprovalStage1','Advance Payment Requisition Approval Stage1','screen','Finance',615),
 ('frmAdvancePaymentRequisitionApprovalStage1_Cancel','Advance Payment Requisition Approval Stage1 Cancel','screen','Finance',616),
 ('frmAdvancePaymentRequisitionApprovalStage2','Advance Payment Requisition Approval Stage2','screen','Finance',617),
 ('frmAdvancePaymentRequisitionApprovalStage2_Cancel','Advance Payment Requisition Approval Stage2 Cancel','screen','Finance',618),
 ('frmPayment','Payment','screen','Finance',619),
 ('frmPaymentDetails','Payment Details','screen','Finance',620),
 ('frmPaymentVoucherPrint','Payment Voucher Print','screen','Finance',621),
 ('frmPaymetApproval','Paymet Approval','screen','Finance',622),
 ('frmPaymentCancel','Payment Cancel','screen','Finance',623),
 ('frmPaymentApprovalDetails','Payment Approval Details','screen','Finance',624),
 ('frmAdvancePaymentMapping','Advance Payment Mapping','screen','Finance',625),
 ('frmPayment_AdvanceMappingPrint','Payment Advance Mapping Print','screen','Finance',626),
 ('frmAdvanceReceiptMapping','Advance Receipt Mapping','screen','Finance',627),
 ('frmCustomerJournal','Customer Journal','screen','Finance',628),
 ('frmCustomerJournalDetails','Customer Journal Details','screen','Finance',629),
 ('rptCustomerJournal_Slip','Customer Journal Slip','screen','Finance',630),
 ('frmCreditNote','Credit Note','screen','Finance',631),
 ('frmCreditNoteDetails','Credit Note Details','screen','Finance',632),
 ('frmCreditNotePrint','Credit Note Print','screen','Finance',633),
 ('frmCreditNoteApproval','Credit Note Approval','screen','Finance',634),
 ('frmCreditNoteApprovalDetails','Credit Note Approval Details','screen','Finance',635),
 ('frmDebitNote','Debit Note','screen','Finance',636),
 ('frmDebitNoteDetails','Debit Note Details','screen','Finance',637),
 ('frmDebitNotePrint','Debit Note Print','screen','Finance',638),
 ('frmDebitNoteApproval','Debit Note Approval','screen','Finance',639),
 ('frmDebitNoteApprovalDetails','Debit Note Approval Details','screen','Finance',640),
 ('rptReceiptDetails','Receipt Details','screen','Finance',641),
 ('rptReceiptApprovalPendingStage1DateWise','Receipt Approval Pending Stage1 Date Wise','screen','Finance',642),
 ('rptReceiptApprovalPendingStage2DateWise','Receipt Approval Pending Stage2 Date Wise','screen','Finance',643),
 ('rptReceiptApprovalStage1DateWise','Receipt Approval Stage1 Date Wise','screen','Finance',644),
 ('rptReceiptApprovalStage2DateWise','Receipt Approval Stage2 Date Wise','screen','Finance',645),
 ('rptCreditNoteDetails','Credit Note Details','screen','Finance',646),
 ('rptCreditNoteApprovalDetails','Credit Note Approval Details','screen','Finance',647),
 ('rptDebitNoteDetails','Debit Note Details','screen','Finance',648),
 ('rptDebitNoteApprovalDetails','Debit Note Approval Details','screen','Finance',649),
 ('rptPaymentDetails','Payment Details','screen','Finance',650),
 ('rptPaymentApprovalPendingDetails','Payment Approval Pending Details','screen','Finance',651),
 ('rptPaymentApprovalDetails','Payment Approval Details','screen','Finance',652),
 ('rptAdvanceRequisitionDetails','Advance Requisition Details','screen','Finance',653),
 ('rptAdvanceRequisitionApprovalStage1','Advance Requisition Approval Stage1','screen','Finance',654),
 ('rptAdvanceRequisitionApprovalStage2','Advance Requisition Approval Stage2','screen','Finance',655),
 ('rptPayment_AdvanceDetails','Payment Advance Details','screen','Finance',656),
 ('rptAdvanceRequisitionApprovalDateWise','Advance Requisition Approval Date Wise','screen','Finance',657),
 ('rptAdvanceRequisitionApprovalStage2DateWise','Advance Requisition Approval Stage2 Date Wise','screen','Finance',658),
 ('rptCustomerJournalDetails','Customer Journal Details','screen','Finance',659),
 ('rptCustomerLedgerDetailed','Customer Ledger Detailed','screen','Finance',660),
 ('rptSupplierLedgerDetailed','Supplier Ledger Detailed','screen','Finance',661),
 ('rptFinancialStatement','Financial Statement','screen','Finance',662);

MERGE dbo.tbl_web_Menu AS t
USING @menu AS s ON t.MenuKey = s.MenuKey
WHEN MATCHED THEN
  UPDATE SET MenuLabel = s.MenuLabel, MenuType = s.MenuType,
             GroupName = s.GroupName, SortOrder = s.SortOrder, Status = 1
WHEN NOT MATCHED THEN
  INSERT (MenuKey, MenuLabel, MenuType, GroupName, SortOrder, Status)
  VALUES (s.MenuKey, s.MenuLabel, s.MenuType, s.GroupName, s.SortOrder, 1);
GO

/* --------------------- Bootstrap the Super Admin role -------------- *
   The ONLY place IsSuperAdmin is granted. The API never sets it.       */
IF NOT EXISTS (SELECT 1 FROM dbo.tbl_web_Role WHERE IsSuperAdmin = 1)
BEGIN
  INSERT INTO dbo.tbl_web_Role (RoleName, IsSuperAdmin, Status, CreatedOn)
  VALUES (N'Super Admin', 1, 1, GETDATE());
END
GO

/* --------------------- Assign yourself as Super Admin -------------- *
   EDIT @AdminUName below to your login username, then run this block.
   (UserCode is looked up from vw_User. Adjust the view/column if needed.)
*/
DECLARE @AdminUName NVARCHAR(100) = N'admin';   -- <<< CHANGE ME

DECLARE @AdminUserCode INT =
  (SELECT TOP 1 UserCode FROM dbo.vw_User WHERE UName = @AdminUName);

DECLARE @SuperRoleCode INT =
  (SELECT TOP 1 RoleCode FROM dbo.tbl_web_Role WHERE IsSuperAdmin = 1 ORDER BY RoleCode);

IF @AdminUserCode IS NOT NULL AND @SuperRoleCode IS NOT NULL
BEGIN
  MERGE dbo.tbl_web_UserRole AS t
  USING (SELECT @AdminUserCode AS UserCode) AS s ON t.UserCode = s.UserCode
  WHEN MATCHED THEN UPDATE SET RoleCode = @SuperRoleCode
  WHEN NOT MATCHED THEN INSERT (UserCode, RoleCode) VALUES (@AdminUserCode, @SuperRoleCode);

  PRINT 'Super Admin assigned to UserCode ' + CAST(@AdminUserCode AS NVARCHAR(20));
END
ELSE
  PRINT 'Could not find user "' + @AdminUName + '". Edit @AdminUName and re-run the bootstrap block.';
GO
